In [1]:
from SPARQLWrapper import SPARQLWrapper, JSON

In [2]:
import pandas as pd

### Classes declared

In [3]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT * 
WHERE 
{ 
  { ?class a owl:Class }
  UNION
  { ?class a rdfs:Class }

  ?class a ?classType
}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['class', 'classType']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'class': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Thing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#Nothing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#List'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#List'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Resource'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Resource'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_013'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_050'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_110'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_body_agreement_international'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_legislative_other_oj_c'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_council'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_ep'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_oj_l'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory_organ_other'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_surveillance-authority_efta'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agent'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agreement_international'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agreement_non-member-states'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#arrangement_institutional'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#assessment_impact_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#assessment_impact_summary_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#budget'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_national'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case_court'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#collection_document'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#com_package'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_case_new'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_cjeu'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_judgement'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#concept_new_case-law'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#concept_type_act'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#container_case-law'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#country'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#decision'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#decision_ecsc'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#decision_implementing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#decision_representatives_member-states'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#directive'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#document_budget_ep'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#document_cjeu'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#document_com_other_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#document_efta'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#dossier'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#event'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#event_case'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#event_legal'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#evolutive_work'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#expression'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#fragment_resource_legal'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#initiative_eums'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#institution'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#item'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#judgement'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#language'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#legislation_complementary'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#legislation_secondary'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_case-law'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_court-report_part'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal_part'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_special-court-report_part'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_special-official-journal_part'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#measure_national_implementing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#monolanguage'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#non-opposition_concentration_notified'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#official-journal'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#oj_c'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_advocate-general'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_consultation_cor'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_consultation_eesc'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_ec_ep-amendments'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_ecb'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_eesc'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_other_cor'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_other_eesc'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#person'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#position_council'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#procedure_code_interinstitutional'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#procedure_without_code_interinstitutional'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#proposal_act'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#proposal_other'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#proposal_regulation_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#publication_general'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#question_oral'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#question_parliamentary'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#question_parliamentary_question_time'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#question_written'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#recommendation'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#regulation'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#regulation_implementing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#report_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#report_eca'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'class': {'type': 'uri',

In [9]:
result_value=[]
for r in results["results"]["bindings"]:
    result_value.append({"class":r["class"]["value"],"class_type":r["class"]["type"],"classType":r["classType"]["value"],"classType_type":r["classType"]["type"]})

In [10]:
df=pd.DataFrame(result_value)
df

,class,class_type,classType,classType_type
0,http://www.w3.org/2002/07/owl#Thing,uri,http://www.w3.org/2002/07/owl#Class,uri
1,http://www.w3.org/2002/07/owl#Nothing,uri,http://www.w3.org/2002/07/owl#Class,uri
2,http://www.w3.org/1999/02/22-rdf-syntax-ns#List,uri,http://www.w3.org/2002/07/owl#Class,uri
3,http://www.w3.org/1999/02/22-rdf-syntax-ns#List,uri,http://www.w3.org/2000/01/rdf-schema#Class,uri
4,http://www.w3.org/2000/01/rdf-schema#Resource,uri,http://www.w3.org/2002/07/owl#Class,uri
...,...,...,...,...
594,http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt,uri,http://www.w3.org/2000/01/rdf-schema#Class,uri
595,http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag,uri,http://www.w3.org/2000/01/rdf-schema#Class,uri
596,http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq,uri,http://www.w3.org/2000/01/rdf-schema#Class,uri
597,http://www.w3.org/2000/01/rdf-schema#Container,uri,http://www.w3.org/2000/01/rdf-schema#Class,uri
598,http://www.w3.org/2000/01/rdf-schema#Container...,uri,http://www.w3.org/2000/01/rdf-schema#Class,uri

In [11]:
df.to_csv("classes.csv",index=False,sep="|",encoding="utf-8")

### Properties used

In [35]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT DISTINCT ?property
WHERE 
{ ?s ?property ?o . }
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['property']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#version'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#loadAs'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#item'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#isSpecialPredicate'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#isGcResistantType'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfLongTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfSqlvalTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfBoolTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsrefOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsuriOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsblankOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIslitOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmf01uriOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmf01blankOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfLongOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfSqlvalOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfDatatypeOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfLanguageOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfBoolOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIidOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfUriOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfStrsqlvalOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfShortOfTypedsqlvalTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfShortOfSqlvalTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfShortOfLongTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfShortOfUriTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsBijection'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfMapsOnlyNullToNull'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsStable'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsSubformatOfLong'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsSubformatOfLongWhenRef'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfCmpFuncName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfTypeminTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfTypemaxTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfColumnCount'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfOkForAnySqlvalue'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfValRange-rvrRestrictions'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfUriIdOffset'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfSuperFormats'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#_1'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#_2'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#_3'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#inheritFrom'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#noInherit'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#_4'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#_5'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfSparqlEbvTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfSparqlEbvOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfExistingShortOfTypedsqlvalTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfExistingShortOfSqlvalTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfExistingShortOfLongTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfExistingShortOfUriTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsSubformatOfLongWhenEqToSql'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfWrapDistinct'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfSubFormatForRefs'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfIsnumericOfShortTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfShortOfNiceSqlvalTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfDtpOfNiceSqlval'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfHasCheapSqlval'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfDatatypeTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfLanguageTmpl'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfValRange-rvrDatatype'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfCustomString1'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmfValRange-rvrLanguage'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmGraphMap'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmSubjectMap'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmPredicateMap'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmObjectMap'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmTableName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmMatchingFlags'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvTableName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvATables'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvColumns'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvFormat'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvColumnsFormKey'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvcAlias'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvcColumnName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvFText'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvGeo'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvaAlias'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvaTableName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvftColumnName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvftXmlIndex'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvftAlias'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvftConds'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qmvftTableName'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qsUserMaps'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qsDefaultMap'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/virtrdf#qsMatchingFlags'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#subPropertyOf'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#equivalentClass'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#equivalentProperty'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#inverseOf'}},
   {'property': {'type': 'uri', 'value': 'http://purl.org/dc/terms/created'}},
   {'property': {'type': 'uri', 'value': 'http://purl.org/dc/terms/modified'}},
   {'property': {'type': 'uri',
     'value': 'http://www.openlinksw.com/schemas/DAV#ownerUser'}},
   {'property': {'type': 'uri', 'value': 'http://purl.org/dc/terms/extent'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#label'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#first'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#complementOf'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#rest'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#unionOf'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#domain'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#range'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#imports'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#comment'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#versionInfo'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#priorVersion'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#disjointWith'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#intersectionOf'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#oneOf'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#onProperty'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#allValuesFrom'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#hasValue'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#someValuesFrom'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#minCardinality'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#maxCardinality'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#cardinality'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#seeAlso'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#type'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_immediately_enforces_resource_legal'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#sameAs'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#subClassOf'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#paragraph'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#expression_case-law_identifier_case'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#lang'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#inScheme'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#annotatedProperty'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#annotatedSource'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#annotatedTarget'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#article'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#build_info'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#comment_on_date'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#comment_on_legal_basis'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#end_of_validity'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#error_message'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#fragment_cited_target'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#fragment_citing_source'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#indent'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#language_list'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#old_value'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#order'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#protocol'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#quality_issue'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#reference_to_modified_location'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#result_decision'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#role2'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#start_of_validity'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#status'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#subparagraph'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#transposition_deadline_transmitted'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#transposition_notification'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#type_of_date'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#type_of_link_target'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated_based_on_resource_legal'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated_consolidates_resource_legal'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated_date'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated_layer'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated_number'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory_date_debate'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agent_name'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_affaire_jurisdiction'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_affaire_number'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_affaire_type'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_affaire_year'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_article_journal_related'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_commented_by_agent'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_defended_by_agent'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_delivered_by_advocate-general'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_delivered_by_judge'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_ecli'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_has_procjur'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_has_type_procedure_concept_type_procedure'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_interpretes_resource_legal'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_is_about_concept_case-law'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_is_about_concept_new_case-law'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_national-judgement'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_national_act_reference_national'}},

In [36]:
result_value=[]
for r in results["results"]["bindings"]:
    result_value.append({"property":r["property"]["value"],"property_type":r["property"]["type"]})

In [37]:
df=pd.DataFrame(result_value)
df

                                              property property_type
0      http://www.w3.org/1999/02/22-rdf-syntax-ns#type           uri
1    http://www.openlinksw.com/schemas/virtrdf#version           uri
2     http://www.openlinksw.com/schemas/virtrdf#loadAs           uri
3       http://www.openlinksw.com/schemas/virtrdf#item           uri
4    http://www.openlinksw.com/schemas/virtrdf#isSp...           uri
..                                                 ...           ...
986  http://www.w3.org/2004/02/skos/core#hasTopconcept           uri
987  http://publications.europa.eu/ontology/euvoc#m...           uri
988  http://publications.europa.eu/ontology/euvoc#n...           uri
989  http://publications.europa.eu/ontology/euvoc#d...           uri
990  http://publications.europa.eu/ontology/euvoc#x...           uri

[991 rows x 2 columns]

In [38]:
df.to_csv("properties.csv",index=False,sep="|",encoding="utf-8")

### Classes use a property

In [24]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://publications.europa.eu/ontology/cdm#>

SELECT ?class
WHERE 
{ :event_title rdfs:domain ?class }
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['class']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#event'}}]}}

In [29]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://publications.europa.eu/ontology/cdm#>

select ?domain ?range where { 
  :treaty_name rdfs:domain ?domain ;
            rdfs:range ?range .
}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['domain', 'range']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'domain': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#treaty'},
    'range': {'type': 'uri',
     'value': 'http://www.w3.org/2001/XMLSchema#string'}}]}}

### List of classes ordered per use

In [32]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?class (COUNT(?s) AS ?instanceTotal)
WHERE
{ ?s a ?class. }
GROUP BY ?class
ORDER BY DESC(?instanceTotal)
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['class', 'instanceTotal']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#item'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '41213446'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#expression'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '33494980'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '23433202'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal_part'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '6987364'}},
   {'class': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#Axiom'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '4252099'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '3669485'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '3324793'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#institution'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '1874076'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#language'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '1475209'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#Label'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '1293782'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#legislation_secondary'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '703851'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#oj_c'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '615406'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '526131'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#regulation'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '481581'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '426750'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_case-law'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '374310'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_court-report_part'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '312715'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#measure_national_implementing'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '286823'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#country'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '257514'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#question_parliamentary'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '237593'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#publication_general'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '217028'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_ec'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '216249'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '208050'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#event_legal'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '206585'}},
   {'class': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#SimpleNonPreferredTerm'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '205570'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#question_written'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '198415'}},
   {'class': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#SimplePreferredTerm'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '191328'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource-type'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '190667'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_special-official-journal_part'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '185705'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#procedure_without_code_interinstitutional'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '150202'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#com_package'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '139649'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_013'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '122469'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#Concept'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '120674'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/euvoc#XlNotation'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '113666'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#decision'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '113461'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#dossier'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '104747'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_110'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '97652'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agent'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '76392'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#table-of-contents'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '68382'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Resource'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '66854'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '66184'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#procedure_code_interinstitutional'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '65489'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#person'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '63808'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/euvoc#XlNote'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '58156'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/ns/dcat#Distribution'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '49687'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law_national'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '49574'}},
   {'class': {'type': 'uri', 'value': 'http://www.w3.org/ns/org#Membership'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '48500'}},
   {'class': {'type': 'uri', 'value': 'http://xmlns.com/foaf/0.1/Person'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '42942'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#official-journal'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '41802'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resolution_other_ep'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '39410'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#document_cjeu'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '38746'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_050'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '38191'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resolution_legislative_ep'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '37670'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#question_parliamentary_question_time'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '35836'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#regulation_implementing'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '34585'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#concept_new_case-law'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '29341'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#organization'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '26262'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#summary_case-law'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '25894'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#judgement'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '25250'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resolution_initiative_own_ep'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '24681'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#treaty'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '23169'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#fragment_resource_legal'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '23111'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#type_event_interinstitutional'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '21881'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#concept_type_act'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '21839'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#event'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '21628'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#document_efta'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '21075'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_council'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '20688'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#opinion_ec'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '19772'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#proposal_act'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '19357'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory_organ_other'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '19255'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#monolanguage'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '18770'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_cjeu'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '17965'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_555'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '17465'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/authority/MappedCode'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '16667'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#ATTO_FD_070'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '16281'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#evolutive_work'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '16052'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_legislative_other_oj_c'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '15389'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agreement_international'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '13601'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#directive'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '13369'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#budget'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '12993'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_surveillance-authority_efta'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '12585'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#subject-matter'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '12180'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_special-court-report_part'},
    'instanceTotal': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#integer',
     'value': '11873'}},
   {'class': {'type': 'uri',

In [33]:
result_value=[]
for r in results["results"]["bindings"]:
    result_value.append({"class":r["class"]["value"],"instanceTotal":r["instanceTotal"]["value"]})

In [35]:
df=pd.DataFrame(result_value)
df

                                                 class instanceTotal
0      http://publications.europa.eu/ontology/cdm#item      41213446
1    http://publications.europa.eu/ontology/cdm#exp...      33494980
2    http://publications.europa.eu/ontology/cdm#man...      23433202
3    http://publications.europa.eu/ontology/cdm#man...       6987364
4                  http://www.w3.org/2002/07/owl#Axiom       4252099
..                                                 ...           ...
410                  http://purl.org/dc/terms/Standard             1
411  http://www.w3.org/2004/02/skos/core#OrderedCol...             1
412  http://publications.europa.eu/ontology/cdm#dec...             1
413            http://www.w3.org/2002/07/owl#DataRange             1
414  http://publications.europa.eu/resource/authori...             1

[415 rows x 2 columns]

In [36]:
df.to_csv("classes_instanceTotal.csv",index=False,sep="|",encoding="utf-8")

### Classes commented

In [4]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT * 
WHERE 
{ 
  { ?class a owl:Class }
  UNION
  { ?class a rdfs:Class }

  ?class a ?classType;
      rdfs:label ?label;
      rdfs:comment ?comment;
      rdfs:subClassOf ?subclass
}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [],
  'vars': ['class', 'classType', 'label', 'comment', 'subclass']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'class': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Nothing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'literal', 'value': 'Nothing'},
    'comment': {'type': 'literal', 'value': 'This is the empty class.'},
    'subclass': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Thing'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#List'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'literal', 'value': 'List'},
    'comment': {'type': 'literal', 'value': 'The class of RDF Lists.'},
    'subclass': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Resource'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#List'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Class'},
    'label': {'type': 'literal', 'value': 'List'},
    'comment': {'type': 'literal', 'value': 'The class of RDF Lists.'},
    'subclass': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Resource'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_body_agreement_international'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Act of body created by international agreement'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Act of body created by international agreement (subsector D of sector 2 in Eur-Lex)'},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agreement_international'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067591'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067649'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067663'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067683'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067809'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067810'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067811'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067812'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_legislative_other_oj_c'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'OJ C other legislative act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': ' Other legislative acts published in Official Journal C series (subsector Y of sector 3) Examples: 31960Y0317(02), 31962Y1109(03), 31970Y0721(01), 31991Y0419(01), 31990Y0303(03).\nRemark:\n\nThere are at present 1189 notices. Other than in sector C the notices referes to legislative acts and they have a real CELEX sector 3 number.'},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#legislation_secondary'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_council'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other act of the Council'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Where its (resource_legal_type = XG, resource_legal_id_sector = 5, work_created_by_agent = CONSIL) OR (resource_legal_id_sector = C, work_created_by_agent = CONSIL)\n'},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory_council'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Commission other act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '7868 Other Commission acts (5XC)'},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_oj_l'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other acts in OJ L'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other acts published in Official Journal L series (= subsector X of sector 4)'},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#legislation_complementary'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Preparatory act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'As per the decision of the meeting of 2010-05-11 the works in sector 5 will be split in real preparatory acts and others such as the report of the Court of Auditors. They will be distinguished by document type and author (e.g. the opinion of the ECB). The preparatory acts have thus been restructured to clearly distinguish between preparatory acts in a strict sense (COMs etc.) and other types of documents that have traditionally been grouped in sector 5.\n\n'},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Preparatory act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'As per the decision of the meeting of 2010-05-11 the works in sector 5 will be split in real preparatory acts and others such as the report of the Court of Auditors. They will be distinguished by document type and author (e.g. the opinion of the ECB). The preparatory acts have thus been restructured to clearly distinguish between preparatory acts in a strict sense (COMs etc.) and other types of documents that have traditionally been grouped in sector 5.\n\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067659'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Preparatory act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'As per the decision of the meeting of 2010-05-11 the works in sector 5 will be split in real preparatory acts and others such as the report of the Court of Auditors. They will be distinguished by document type and author (e.g. the opinion of the ECB). The preparatory acts have thus been restructured to clearly distinguish between preparatory acts in a strict sense (COMs etc.) and other types of documents that have traditionally been grouped in sector 5.\n\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067879'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Preparatory act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'As per the decision of the meeting of 2010-05-11 the works in sector 5 will be split in real preparatory acts and others such as the report of the Court of Auditors. They will be distinguished by document type and author (e.g. the opinion of the ECB). The preparatory acts have thus been restructured to clearly distinguish between preparatory acts in a strict sense (COMs etc.) and other types of documents that have traditionally been grouped in sector 5.\n\n'},
    'subclass': {'type': 'bnode', 'value': 'nodeID://b57067880'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory_organ_other'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other organ preparatory act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': "810 Other organs' or bodies' preparatory acts, e.g. national governments (5XX)"},
    'subclass': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_surveillance-authority_efta'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Act of EFTA Surveillance Authority'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',

In [5]:
result_value=[]
for r in results["results"]["bindings"]:
    result_value.append({"class":r["class"]["value"],"label":r["label"]["value"],"comment":r["comment"]["value"],"subclass":r["subclass"]["value"]})

In [6]:
df=pd.DataFrame(result_value)
df

,class,label,comment,subclass
0,http://www.w3.org/2002/07/owl#Nothing,Nothing,This is the empty class.,http://www.w3.org/2002/07/owl#Thing
1,http://www.w3.org/1999/02/22-rdf-syntax-ns#List,List,The class of RDF Lists.,http://www.w3.org/2000/01/rdf-schema#Resource
2,http://www.w3.org/1999/02/22-rdf-syntax-ns#List,List,The class of RDF Lists.,http://www.w3.org/2000/01/rdf-schema#Resource
3,http://publications.europa.eu/ontology/cdm#act...,Act of body created by international agreement,Act of body created by international agreement...,http://publications.europa.eu/ontology/cdm#agr...
4,http://publications.europa.eu/ontology/cdm#act...,Consolidated act,Consolidated acts (= sector 0): Non-official d...,http://publications.europa.eu/ontology/cdm#res...
...,...,...,...,...
1550,http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt,Alt,The class of containers of alternatives.,http://www.w3.org/2000/01/rdf-schema#Container
1551,http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag,Bag,The class of unordered containers.,http://www.w3.org/2000/01/rdf-schema#Container
1552,http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq,Seq,The class of ordered containers.,http://www.w3.org/2000/01/rdf-schema#Container
1553,http://www.w3.org/2000/01/rdf-schema#Container,Container,The class of RDF containers.,http://www.w3.org/2000/01/rdf-schema#Resource
1554,http://www.w3.org/2000/01/rdf-schema#Container...,ContainerMembershipProperty,"The class of container membership properties, ...",http://www.w3.org/1999/02/22-rdf-syntax-ns#Pro...

In [10]:
#df.to_csv("classes_commented.csv",index=False,sep="{",encoding="utf-8")

In [11]:
df.to_excel("classes_commented.xlsx",index=False,encoding="utf-8")

### Classes commented without subclass

In [12]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT * 
WHERE 
{ 
  { ?class a owl:Class }
  UNION
  { ?class a rdfs:Class }

  ?class a ?classType;
      rdfs:label ?label;
      rdfs:comment ?comment
}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['class', 'classType', 'label', 'comment']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'class': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Thing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'literal', 'value': 'Thing'},
    'comment': {'type': 'literal', 'value': 'The class of OWL individuals.'}},
   {'class': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#Nothing'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'literal', 'value': 'Nothing'},
    'comment': {'type': 'literal', 'value': 'This is the empty class.'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#List'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'literal', 'value': 'List'},
    'comment': {'type': 'literal', 'value': 'The class of RDF Lists.'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#List'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Class'},
    'label': {'type': 'literal', 'value': 'List'},
    'comment': {'type': 'literal', 'value': 'The class of RDF Lists.'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Resource'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'literal', 'value': 'Resource'},
    'comment': {'type': 'literal',
     'value': 'The class resource, everything.'}},
   {'class': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Resource'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Class'},
    'label': {'type': 'literal', 'value': 'Resource'},
    'comment': {'type': 'literal',
     'value': 'The class resource, everything.'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_body_agreement_international'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Act of body created by international agreement'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Act of body created by international agreement (subsector D of sector 2 in Eur-Lex)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_consolidated'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Consolidated acts (= sector 0): Non-official documents integrating acts of sector 3 with their amendments and corrections.\n\nNote: The original VOLET_CONSLEG contains also more fields:\n* CONSOLID_SEQ: Sequence in the list\n* CONSOLID_ACT set: Logical grouping element: Used if the act is modified\n* CONSOLID_ROLE: "IN ou OUT suivant prise en compte dans consolidation"\n* CONSOLID_FICHE: contains links from the acts to the consolidating acts\n* BF_NAT, BF, LE and TM are old Consolidation fields that need to be taken into account\n\nThe pertinence of these fields must be discussed\n'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_legislative_other_oj_c'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'OJ C other legislative act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': ' Other legislative acts published in Official Journal C series (subsector Y of sector 3) Examples: 31960Y0317(02), 31962Y1109(03), 31970Y0721(01), 31991Y0419(01), 31990Y0303(03).\nRemark:\n\nThere are at present 1189 notices. Other than in sector C the notices referes to legislative acts and they have a real CELEX sector 3 number.'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_council'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other act of the Council'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Where its (resource_legal_type = XG, resource_legal_id_sector = 5, work_created_by_agent = CONSIL) OR (resource_legal_id_sector = C, work_created_by_agent = CONSIL)\n'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Commission other act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '7868 Other Commission acts (5XC)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_other_oj_l'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other acts in OJ L'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other acts published in Official Journal L series (= subsector X of sector 4)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Preparatory act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'As per the decision of the meeting of 2010-05-11 the works in sector 5 will be split in real preparatory acts and others such as the report of the Court of Auditors. They will be distinguished by document type and author (e.g. the opinion of the ECB). The preparatory acts have thus been restructured to clearly distinguish between preparatory acts in a strict sense (COMs etc.) and other types of documents that have traditionally been grouped in sector 5.\n\n'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_preparatory_organ_other'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Other organ preparatory act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': "810 Other organs' or bodies' preparatory acts, e.g. national governments (5XX)"}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#act_surveillance-authority_efta'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Act of EFTA Surveillance Authority'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Act of the European Free Trade Association (EFTA) Surveillance Authority (= subsector C of sector E in EUR-Lex)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agent'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Agent'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '"A resource that acts or has the power to act. Examples of Agent include person, organization, and software agent" (Dublin Core) '}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agreement_international'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'International agreement'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'International agreements (= sector 2 in EUR-Lex)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#agreement_non-member-states'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Agreement with non-member states'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Agreement with non-member states or international organizations (subsector A of sector 2 in Eur-Lex) '}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#arrangement_institutional'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Institutional arrangement'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': ' Institutional arrangements: rules of procedure; internal agreements (subsector Q of sector 3). At present 267 notices. Examples: 31953Q0003, 31957Q0002, 31969Q0491, 32009Q0716(02), 32005Q1029(01)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#assessment_impact_summary_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'European Commission Summary of Impact Assessment'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Summary of Impact Assessment documents for the European Commission'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#budget'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Budget'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Subsector B of sector 3. At present 912 notices. Examples: 31970B0183,31979B0476.32010B0117R(01), 32010B0162 '}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case-law'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Case law'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '"Real" case law in sector 6 (= a subset of the complete sector 6) and sector 8.\nChanged to subclass of: resource_legal.\n\nCase law of the Court of Justice also inherits from document_cjeu\n\nRemarks:\n* case-law_XXX_resource_legal can all be seen as sub-properties of a generic "affects" property\n* These fields by and large correspond to the specific fields of the VOLET_CDJ\n* NOMUSUEL and NOMUSUEL_XX: Appears as title in the corresponding expression'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#case_court'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Case at a Court'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Case at a Court (pending or closed)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#collection_document'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Document collection'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'A collection of documents. Typical examples might be the collection of documents with a Celex ID, with an ID Pub etc.'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#com_package'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'COM Package'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Package of digitized documents related to a COM proposal. \nHistorical collection of documents related to a Commission proposal, digitized based on the fonds of the OIB archive. Such COM packages merge typically a number of different documents across linguistic versions in a single multilingual expression. \n\nEach expression indicates the languages it uses, each title has in a language tag the corresponding language.\n\nThe relationship between the COM package and its COM is expressed via work_contains_work. The COM identifier can be built based on ext:prefix_com, ext:year_com and ext:number_com.'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_case_new'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Communication on a new case'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Communication on a New Case in sector 6'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_cjeu'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Court communication'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Communication of the court of justice (in sector 6)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_ec'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Commission communication'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '3063 Commission communication (5DC or 5SC with FM=COMMUNIC)'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#communication_judgement'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Communication on a judgement'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Communication on a Judgement in sector 6 '}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#concept_new_case-law'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'New case law concept'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Concept from the case law directory .\nThe case law concept is currently coded with FD_Table 577'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#concept_type_act'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Concept representing the type of an act'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Corresponds to the contents of the Procat field FM, coded with FD_Table 030. This concept belonging  to the deprecated NAL fd_030 is not anymore fed. Please use the concept resource-type which has replaced it.'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#container_case-law'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Container work for case law'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'A container work regrouping multiple case law documents for publication purposes. \n\nThis work in particular regroups multiple related case law documents for publication and display on EUR-Lex. Typically, the case law container is identified by a numpub.\n\nUse the general work_part_of_work relationship to indicate that a case law is part of a case law collection'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#country'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Country'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': ' Country. The list of instances of this class is provided by the Metadata Registry.\n\nA country can in our context both act as an agent and as an administrative unit. '}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#decision'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Decision'},
    'comment': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Subsector D of sector 3. At present 27222 notices'}},
   {'class': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#decision_ecsc'},
    'classType': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#Class'},
    'label': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'ECSC decision'},

In [13]:
result_value=[]
for r in results["results"]["bindings"]:
    result_value.append({"class":r["class"]["value"],"label":r["label"]["value"],"comment":r["comment"]["value"]})

In [14]:
df=pd.DataFrame(result_value)
df

,class,label,comment
0,http://www.w3.org/2002/07/owl#Thing,Thing,The class of OWL individuals.
1,http://www.w3.org/2002/07/owl#Nothing,Nothing,This is the empty class.
2,http://www.w3.org/1999/02/22-rdf-syntax-ns#List,List,The class of RDF Lists.
3,http://www.w3.org/1999/02/22-rdf-syntax-ns#List,List,The class of RDF Lists.
4,http://www.w3.org/2000/01/rdf-schema#Resource,Resource,"The class resource, everything."
...,...,...,...
514,http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt,Alt,The class of containers of alternatives.
515,http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag,Bag,The class of unordered containers.
516,http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq,Seq,The class of ordered containers.
517,http://www.w3.org/2000/01/rdf-schema#Container,Container,The class of RDF containers.
518,http://www.w3.org/2000/01/rdf-schema#Container...,ContainerMembershipProperty,"The class of container membership properties, ..."

In [15]:
df.to_excel("classes_commented_nosubclass.xlsx",index=False,encoding="utf-8")

In [57]:
uri="http://eurovoc.europa.eu/100141"
uri="http://eurovoc.europa.eu/1001550"
uri="http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01"
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
        SELECT DISTINCT ?s ?p ?o 
        where {{?s ?p ?o.} 
               bind (if(ISBLANK(?o),<LONG::bif:iri_id_num>(?o),'') as ?oID).
               bind (if(LANG(?o),LANG(?o),'') as ?oLANG).
               FILTER(?oLANG='en'||?oLANG='')
               filter(?s=<"""+uri+""">)}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['s', 'p', 'o']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#sameAs'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/oj/JOC_2017_058_R.HUN.pdfa1a'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#sameAs'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/uriserv/OJ.C_.2017.058.FULL.HUN.pdfa1a'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_is-signed'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#boolean',
     'value': '1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_issn'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '19770979'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_manifests_expression'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_number_catalogue'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'FXAC17058HUC'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal_page_first'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '0001'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal_page_last'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '0039'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_official-journal_pages_total'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '39'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_signed_by_signature_digital'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0b11c68e-f99b-11e6-8a35-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_type'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'pdfa1a'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#creationDate'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
     'value': '2017-02-23T08:37:47.138+01:00'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f5a6126c-f99a-11e6-8a35-01aa75ed71a1.0011.01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#lastModificationDate'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
     'value': '2017-02-23T08:37:40.718+01:00'}}]}}

In [26]:
uri="http://publications.europa.eu/resource/authority/pub-theme/A01"
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
SELECT DISTINCT ?s ?p ?o 
where {{?s ?p ?o.} 
       filter(?s=<"""+uri+""">)}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['s', 'p', 'o']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#concept_op_theme'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'o': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#Concept'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/euvoc#PubTheme'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri', 'value': 'http://purl.org/dc/terms/created'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2014-11-26'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#versionInfo'},
    'o': {'type': 'literal', 'value': '20190619-0'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#inScheme'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'sk', 'value': 'Budovanie Európy'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'cs', 'value': 'Budování Evropy'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'es',
     'value': 'Construcción europea'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'fr',
     'value': 'Construction européenne'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'en',
     'value': 'Construction of Europe'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'ro',
     'value': 'Construcția europeană'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'pt',
     'value': 'Construção europeia'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'it',
     'value': 'Costruzione europea'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'lv', 'value': 'Eiropas veidošana'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'et',
     'value': 'Euroopa ülesehitamine'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'fi',
     'value': 'Euroopan yhdentyminen'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'sv',
     'value': 'Europeisk uppbyggnad'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'lt', 'value': 'Europos kūrimas'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'de',
     'value': 'Europäisches Aufbauwerk'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'da',
     'value': 'Europæisk integration'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'hu', 'value': 'Európa építése'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'hr', 'value': 'Izgradnja Europe'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'sl', 'value': 'Izgradnja Evrope'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'mt',
     'value': 'Kostruzzjoni tal-Ewropa'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'nl', 'value': 'Opbouw van Europa'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'pl', 'value': 'Tworzenie Europy'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal', 'xml:lang': 'ga', 'value': 'Tógáil na hEorpa'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'el',
     'value': 'Οικοδόμηση της Ευρώπης'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#prefLabel'},
    'o': {'type': 'literal',
     'xml:lang': 'bg',
     'value': 'Изграждане на Европа'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/euvoc#startDate'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '1999-01-01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri', 'value': 'http://lemon-model.net/lemon#context'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/use-context/IMMC'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri', 'value': 'http://lemon-model.net/lemon#context'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/use-context/PUB'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22537757'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22537863'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22538133'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22538957'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22538969'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22539522'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22539685'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22539803'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22539869'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540287'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540332'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540446'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540534'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540535'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540536'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540537'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540538'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540539'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540540'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540541'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540542'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540543'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540544'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#prefLabel'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540545'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#notation'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://publications.europa.eu/ontology/euvoc#PUB_THEM14',
     'value': 'A01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#topConceptOf'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/euvoc#status'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/concept-status/CURRENT'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/euvoc#xlNotation'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540489'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broader'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://purl.org/dc/elements/1.1/identifier'},
    'o': {'type': 'literal', 'value': 'A01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/authority/authority-code'},
    'o': {'type': 'literal', 'value': 'A01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/authority/deprecated'},
    'o': {'type': 'literal', 'value': 'false'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/authority/op-code'},
    'o': {'type': 'literal', 'value': 'A01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/authority/start.use'},
    'o': {'type': 'literal', 'value': '1999-01-01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/op-code'},
    'o': {'type': 'literal', 'value': 'A01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/authority/op-mapped-code'},
    'o': {'type': 'bnode', 'value': 'nodeID://b22540533'}}]}}

In [30]:
uri="http://publications.europa.eu/ontology/cdm#resource_legal_related_to_resource_legal"
uri="http://publications.europa.eu/resource/cellar/9dc4ac11-dcff-11e3-8cd4-01aa75ed71a1"
uri="http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1"
uri="http://publications.europa.eu/resource/genpub/2020.2099"
uri="http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1"
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
        SELECT DISTINCT ?s ?p ?o 
        where {{?s ?p ?o.} 
               bind (if(ISBLANK(?o),<LONG::bif:iri_id_num>(?o),'') as ?oID).
               bind (if(LANG(?o),LANG(?o),'') as ?oLANG).
               FILTER(?oLANG='en'||?oLANG='')
               filter(?s=<"""+uri+""">)}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['s', 'p', 'o']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#publication_general'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#sameAs'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/genpub/2020.2099'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#date_creation_legacy'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2020-05-12'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#publication_general_has_target_audience'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/target-audience/GEN'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#publication_general_is_about_concept_op_theme'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/pub-theme/A01'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_authored_by_agent'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/corporate-body/REPRES_LUX'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_date_creation_legacy'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2020-05-12'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_date_document'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2020-05-09'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_has_resource-type'},
    'o': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/resource-type/PUB_GEN'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_id_document'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '2020.2099'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_is_about_concept_eurovoc'},
    'o': {'type': 'uri', 'value': 'http://eurovoc.europa.eu/4061'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#creationDate'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
     'value': '2020-05-12T04:55:10.196+02:00'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fe6641fd-93fb-11ea-aac4-01aa75ed71a1'},
    'p': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#lastModificationDate'},
    'o': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
     'value': '2021-01-11T04:25:10.899+01:00'}}]}}

In [22]:
uri="http://publications.europa.eu/ontology/cdm#case-law_national"
uri="http://www.w3.org/2000/01/rdf-schema#Resource"
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?entity
WHERE {
    ?entity rdf:type/rdfs:subClassOf* <"""+uri+""">
}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['entity']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#microThesaurus'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#metsStructSubDiv'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#microThesaurus'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#metsStructSubDiv'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#microThesaurus'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#metsStructSubDiv'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#microThesaurus'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#metsStructSubDiv'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_related_to_manifestation'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_question_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_related_to_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_is_another_publication_of_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_tackles_similar_question_as_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#translationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#dossier_related_to_dossier'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#related_to'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#labelRelation'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_related_to_manifestation'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_question_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_related_to_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_is_another_publication_of_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_tackles_similar_question_as_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#translationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#dossier_related_to_dossier'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#related_to'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#labelRelation'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_related_to_manifestation'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_question_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_related_to_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_is_another_publication_of_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_tackles_similar_question_as_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#translationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#dossier_related_to_dossier'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#related_to'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#labelRelation'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#manifestation_related_to_manifestation'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_related_question_to_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_related_to_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_is_another_publication_of_work'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#resource_legal_tackles_similar_question_as_resource_legal'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#translationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#dossier_related_to_dossier'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#related_to'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2008/05/skos-xl#labelRelation'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#closeMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#related'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#relatedMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#lang'}},
   {'entity': {'type': 'uri', 'value': 'http://www.w3.org/ns/org#member'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/ns/org#organization'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#memberList'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#memberList'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/op-code'}},
   {'entity': {'type': 'uri', 'value': 'http://eurovoc.europa.eu/schema#USE'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#language'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#compoundNonPreferredTerm'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#exportDate'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#exportVersion'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#exportedThesaurus'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#domain'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#metsStructSuperDiv'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#qualifier'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#status'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#lang'}},
   {'entity': {'type': 'uri', 'value': 'http://www.w3.org/ns/org#member'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/ns/org#organization'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#memberList'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#memberList'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/op-code'}},
   {'entity': {'type': 'uri', 'value': 'http://eurovoc.europa.eu/schema#USE'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#language'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#compoundNonPreferredTerm'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#exportDate'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#exportVersion'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#exportedThesaurus'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#domain'}},
   {'entity': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#metsStructSuperDiv'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#qualifier'}},
   {'entity': {'type': 'uri',
     'value': 'http://eurovoc.europa.eu/schema#status'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/ns/org#transitiveSubOrganizationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/ns/org#transitiveSubOrganizationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/ns/org#transitiveSubOrganizationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/ns/org#transitiveSubOrganizationOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#broaderTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#exactMatch'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2004/02/skos/core#narrowerTransitive'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#subPropertyOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#equivalentClass'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#equivalentClass'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#equivalentProperty'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#equivalentProperty'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#inverseOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#inverseOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#label'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#first'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#complementOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#complementOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#rest'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#unionOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#unionOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#domain'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#range'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#imports'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#comment'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#versionInfo'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#priorVersion'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#disjointWith'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#disjointWith'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#differentFrom'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#differentFrom'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#distinctMembers'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#distinctMembers'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#intersectionOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#intersectionOf'}},
   {'entity': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#oneOf'}},
   {'entity': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#oneOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#onProperty'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#onProperty'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#allValuesFrom'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#allValuesFrom'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#hasValue'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#hasValue'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#someValuesFrom'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#someValuesFrom'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#minCardinality'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#minCardinality'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#maxCardinality'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#maxCardinality'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#cardinality'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#cardinality'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#seeAlso'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#backwardCompatibleWith'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#incompatibleWith'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#sameAs'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#sameAs'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#subClassOf'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#annotatedProperty'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#annotatedSource'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#annotatedTarget'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#object'}},
   {'entity': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate'}},

In [ ]:
total_results=[]
for index,row in df.iterrows():
    sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

    sparql.setQuery("""
    SELECT ?entity
    WHERE {
        ?entity rdf:type/rdfs:subClassOf* """+className+"""
    }
    """)

    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()

    results

In [34]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
prefix :    <http://stackoverflow.com/q/23223447/1281433/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?property ?value where {
  rdfs:Resource ?property ?value .
}""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['property', 'value']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'value': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'value': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#Class'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#label'},
    'value': {'type': 'literal', 'value': 'Resource'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'},
    'value': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#comment'},
    'value': {'type': 'literal',
     'value': 'The class resource, everything.'}}]}}

In [54]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?class ?s
WHERE
{ ?s a <http://publications.europa.eu/ontology/cdm#summary_case-law>. }
LIMIT 100
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['class', 's']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/072dd385-3cdd-4702-8c05-4d6579112bae'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/08ead514-3dc7-4f1a-b8a8-0de93b9303a6'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/33242362-2994-4ccf-9022-6eaa08686572'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/9c8961a6-64a7-49e2-98d6-89464ec12e2d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/a4700e4b-f5ac-4c05-82fe-785805d4c2de'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/ad95d282-3bfb-4e61-9c07-639cd02f70f5'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/af665616-4d19-11e7-a5ca-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/e5fe4728-2b2a-43c5-b95c-9632341f2474'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f684be3b-ee65-430a-89c7-b1cf9dbf1d63'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0082d73c-727e-4978-8d59-a3f43c1812ad'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/14b25ccb-c6c1-11e6-a6db-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/1b0e49e0-15fd-41f1-a3c2-1592d5a82f10'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/47e65438-2c90-4ea4-a5cc-eaf1ab43b5a5'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/494ef299-6778-4b29-a088-bd9ca802db58'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/7172ddbf-23bb-4ee8-8ef9-427ba138e4cd'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/760be3df-c6c0-11e6-a6db-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/76313318-20f7-4b4b-8a70-662bc61b4c6a'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b468a8ad-3c4e-4d88-8f1b-5230968b4cf7'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b91025cc-6df1-4d6e-a00d-fd89ad35884f'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/bedee48e-47f9-42e9-9275-6fc0f72c97bb'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/e53088c0-9dbd-44f7-9cb1-44560e639bcc'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fbfa73fb-0d6c-4a2f-a008-7b659769536d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/ff7ea9f8-0941-404e-bdbf-5999be8ad0e1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/ff9f4980-a5bc-42b8-835a-d06778c434d2'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/2bf2c3de-09c0-4987-955c-03691af55c5e'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/63cf1fa8-5ebf-46d9-9fc9-6e15c5d457aa'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/888d72e9-38be-43e3-8cdf-01ac04c404ea'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/92c03352-674d-423e-afb1-27fe3df5bda1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/94b27bc9-d587-421d-b133-71adadf61717'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/aeb597c0-4807-4aab-91bf-74580485ea39'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b75e10c7-8f42-4c74-bc28-81e31102b16f'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/dd23ca92-4bc7-479c-8ec6-bb785796ceb8'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/401cc3a6-f2f1-4dbd-934e-b405b0374805'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/578f40bc-6926-4620-a0ef-732ccb8758ca'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/679bc083-83bd-436b-a4da-ff7d3ed80a0e'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/888d2fc4-66b2-4b5d-805e-8dc25807c818'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/a070425a-400e-4fb7-846a-25972100f82d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b5932a9f-f8ff-4cc7-a282-34a6c284f1d6'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/bd6e74af-a3ee-46eb-a700-7826fabe8eb6'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/c64bdd34-909b-11e6-b237-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/c89af0aa-582c-4966-a3c7-8a2c3faa4196'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/eb9dbf49-4cfd-11e7-a5ca-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fa7d2ac5-e06c-48e1-91a4-224f95a6a457'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fb351148-1ab7-40ff-bc15-3daedffa93be'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fd39cd78-2ca1-40f1-8fa6-9a0ab41e6d4e'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0506311d-ee88-41cf-a298-74e8a4003232'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/1b1aedd4-a436-49c5-b26d-dbdbfdd027fb'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/75a9f601-55ba-49a9-b23e-4139aa6a3738'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/86a13da2-4e00-4f8b-b148-668a3a07c789'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/895cad12-e598-4e22-9698-3d4a87e785b0'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/94b21706-0f54-4281-b906-5591faf9665f'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b1f38dc4-9ccf-4727-a28f-d32029e89fc8'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b8fd5b7b-9e86-4d16-b827-acb000a6210f'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/e828f44e-1126-4bf7-b749-8d62ca46ad6c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0fe13546-30d3-4cf2-acc0-78e41d7a0e90'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/18d4bc19-fdbd-11e6-8a35-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/2c7c94f7-7f6e-4ef9-9d9a-2fa790a4ea17'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/3e6eb0c5-d0e3-420b-a7ad-7ae927c98889'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/986a20f1-8e4b-4ecb-b3ff-0c46c8d3d029'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/bc80cce1-2482-46e8-aaca-a2a041044c89'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/d5d1ae50-0098-47fa-917a-107b559fbdcc'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f7db9066-8855-4fcb-a34f-d5040633254b'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/09efe399-eaae-488f-bbff-3588c18314da'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/41339445-2fb1-4fc0-ab9a-52811e703f89'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/47883a2b-2ccb-4ce8-938a-96b789d5e45b'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/6e0a0e25-e498-4e38-9727-e354c31077f3'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/9dd3f468-a0bc-4965-b027-686c59497e80'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/a0229607-3443-4c24-b341-f6a10d9c8cb6'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/de63f9c5-9c17-455d-86d9-54c562b16b03'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/dec2ed77-99dc-42c0-9d6f-40623a60f35c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f1442b7b-f712-4d6a-bfcf-3ffa603061ff'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f9bf19b0-9f70-4bf3-aa8d-2815bc758e9b'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0a2549ab-19a1-4607-893b-c294bf1fbbe7'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/12b51046-8dc6-4d59-8cfa-07ee814081de'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/1c001321-cc9f-11e3-b74e-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/1e289887-7cbb-48ea-88a2-4e0024127e6b'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/27c59313-dd84-11e6-ad7c-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/2df42b02-f5b1-4810-b7d6-ec9eb0458180'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/493f57c4-19cf-4b57-9a69-284536c10584'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/70fb9ea9-188d-4174-902a-107cba0adac0'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/779d288c-675d-4a53-9a19-734dc50fbc9d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/88a2c4e2-6bb4-406a-be5b-39842132f618'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/afaa8013-d1c7-48fa-99f4-7088814ccb64'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/c58f4c51-c5f3-4bbd-bbd4-a5c187530794'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/d22d46ce-14d3-4eed-a31d-2ac4d655dc16'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/e1cb8630-0f16-4e30-a074-67b05faf3fdb'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f71ead54-acc0-49fa-8814-97f3a70b7330'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f807ed27-6eaa-43eb-b63a-f83e8948a507'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/2db3a2ca-ed42-4d28-975d-2c53b16797b2'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/34285d23-0e98-4bfa-868d-106df76df6ce'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/48377154-df4e-4691-abc1-58a44f76feff'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/690eb76f-5bab-4446-b59d-57729bcff587'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/7553c435-6184-4363-aba3-cb853ad246c6'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/7777eba0-072f-4b16-b2bb-a6e64985b56b'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/86711970-b135-49bb-b33d-ba1efe64b2fd'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/933dbdb3-a02d-426f-94c3-4e008f65ab09'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/96cf09c0-0fba-4c96-8bfe-f90948dd58c0'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/c14ecb41-8c8d-4518-8207-c359cf32e19d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/de41da3f-8bff-41b2-ad2e-68f64f40d61c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fbf61f9e-be83-4163-b781-eff343dd0f63'}}]}}

In [ ]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?class ?s
WHERE
{ ?s a <http://publications.europa.eu/ontology/cdm#summary_case-law>. }
LIMIT 100
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

In [50]:
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?class ?s
WHERE
{ ?s a <http://www.w3.org/2000/01/rdf-schema#Resource>. }
LIMIT 50
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['class', 's']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5e12ff67-7b37-4032-a52d-82eeab4f887d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5e617009-9cba-4edf-acfe-6954c7176e8b'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/024446d5-3904-452f-bf18-f3484cadef7c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/024fdf2f-f551-45e2-b744-1bb855793dc6'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/10624352-8de2-48d8-bc75-0856007a3fb9'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/10acd98e-6453-4893-97d1-222f633a9ee1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/13aa0910-8c2c-4e8e-b28e-4f275912e9d0'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/18806920-f9c8-45ed-b93a-422bacbfc226'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/1cdfd433-aef9-11e7-837e-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/216172e2-fa03-4c6f-b5f1-d4f8de8aea69'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/2ce5c315-be42-45b6-a8c6-b42ff11348c3'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/2d766832-4658-4c7f-9dba-9dc2c695a7e5'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/38b1d03f-084d-11e6-b713-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5424fe8b-71d5-4c92-9ebe-c7bead36d73c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5c97d3fd-a51e-44d7-8a30-1bf72fa8452c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/631a579a-5f55-46e5-a0f3-498f0827e53d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/7997d9b8-7b43-4164-a5fd-6ab57c41cb9f'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/a868de48-e989-4f82-97d2-bea6fd058260'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b0edcf90-5650-47c6-8645-df833a8bec7c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/bb1d2c4a-0b71-11e6-b713-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/da1412f2-3a57-4fb7-afc2-5710a155e028'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/e8bf7970-e54d-41f5-bb7a-0a378dd99395'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/ec9e2ec2-3224-4db1-a161-4996c359ed5b'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/fdab9ac0-2d59-496b-80ef-8a42ca22dd99'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/ffbf7f9c-a878-11e5-b528-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/d9627e80-a075-4195-be68-ade4df12d7f4'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f1740437-24cc-11e7-b611-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f6094a3e-2ef2-4bc7-a218-286198a09d77'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0163ceba-018d-42f2-91eb-cb3165b24615'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/08561b34-258b-44c2-8656-94dd60b6b995'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0ae869e8-a3d2-40fe-9f01-80d3d629f61e'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/2c464fc2-c18a-4934-8eed-1766278031b6'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/309b3540-bc99-4577-ae25-eeccdce35b24'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/3c630a8e-ea24-4a43-96f4-68271b54f1bb'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/3cacc032-d301-4c27-9efe-d9cdcb78679f'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/40b7dd58-deb6-4851-9497-365c5938a21e'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/449ce973-9156-45d3-ac7f-86659f6b48b3'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5595da01-f7a9-47b6-add4-b93a8f1ae9f0'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5a5a46e6-46bd-4630-847c-982c2cf4ef8c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5ae0a26c-1da8-4f39-af0d-8d8d9964a72f'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5f1be276-72d6-11e7-b2f2-01aa75ed71a1'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/6446e9e7-9763-48b7-8439-bbf465c0eb42'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/6ba2c914-cea4-4b9b-858e-b801c40770c0'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/6f3270fe-bd7f-48f4-b8c6-7198c8e5f91c'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/71898649-d8ea-4bac-9e20-6236d8e6c43d'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/720da031-d0e2-4377-a172-d3ee77cf4056'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/782cb7b5-7959-45dc-988a-8c6f4b58f223'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/78fbafc9-33ff-4d3f-8ecd-8f8005026330'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/9804e479-5999-4c5d-932d-d8e6704b3d1a'}},
   {'s': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/b80a6dcc-968f-4929-9e67-6e2c2daca826'}}]}}

In [55]:
uri="http://publications.europa.eu/resource/cellar/072dd385-3cdd-4702-8c05-4d6579112bae"
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?property ?value
WHERE
{ ?subject ?property ?value. 
filter(?subject=<"""+uri+""">)}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['property', 'value']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#summary_case-law'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2002/07/owl#sameAs'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/celex/62002CJ0200_SUM'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/annotation#build_info'},
    'value': {'type': 'literal',
     'value': 'cdm:CDM_2.1.7  tdm:1523  xslt:3945 saxon:9.0.0.1J JVM:1.6.0_29 metaconvJar:1.1.8 builddate:07/11/2013 12:06:53'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#publication_general_date_publication'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2004-10-19'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#summary_case-law_id_celex'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': '62002CJ0200_SUM'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#summary_summarizes_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/0278a532-968f-45c4-a8cb-c0d188f64f51'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/67227bb7-edfa-4b22-b9f2-9a209b810dc5'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/a7cf4753-bd9e-44fa-85d2-ca425484a2c5'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5c4de932-dfc6-4d62-b9f3-9c763832d04a'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/620f38cd-4788-4533-a217-81bcc9895e4d'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/4578a163-59aa-419a-87af-430cb63c8fbd'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/f14c8c2a-e2e0-478b-8874-ef13f0b24e41'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/5285e429-5c52-460a-a376-1b9235db3074'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/8c7201db-2d09-4e09-9069-96e66f55fbf1'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/05754145-be7f-4e08-9393-24436dfae03e'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/66bff8a5-4f96-42e5-9a04-5de175a66ae5'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/8b43e371-39c6-417b-bc23-3e0b7640f9fa'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/c45b06af-db55-4e22-9e98-8f8ad0438635'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/13a54434-d317-4715-b6ae-ff73d7221aad'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_cites_work'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/cellar/9ced5303-30b5-49b6-a033-d2e7a06fd871'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_created_by_agent'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/corporate-body/CJ'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_date_creation'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2013-11-07'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_date_creation_legacy'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2004-10-27'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_date_document'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#date',
     'value': '2004-10-19'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_has_resource-type'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/resource-type/SUM_JUR'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_id_document'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'celex:62002CJ0200_SUM'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_id_obsolete_notice'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#positiveInteger',
     'value': '435717'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_part_of_collection_document'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/document-collection/CELEX'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#work_part_of_collection_document'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/resource/authority/document-collection/OP_DATPRO'}},
   {'property': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm/cmr#lastModificationDate'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
     'value': '2020-02-15T01:14:10.640+01:00'}}]}}

In [56]:
uri="http://publications.europa.eu/resource/celex/62002CJ0200_SUM"
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?property ?value
WHERE
{ ?subject ?property ?value. 
filter(?subject=<"""+uri+""">)}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['property', 'value']},
 'results': {'distinct': False, 'ordered': True, 'bindings': []}}

In [52]:
uri="http://publications.europa.eu/ontology/cdm#summary_case-law"
sparql = SPARQLWrapper("https://publications.europa.eu/webapi/rdf/sparql")

sparql.setQuery("""
SELECT ?property ?value
WHERE
{ ?subject ?property ?value. 
filter(?subject=<"""+uri+""">)}
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()

results

{'head': {'link': [], 'vars': ['property', 'value']},
 'results': {'distinct': False,
  'ordered': True,
  'bindings': [{'property': {'type': 'uri',
     'value': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'},
    'value': {'type': 'uri', 'value': 'http://www.w3.org/2002/07/owl#Class'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#label'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Summary of case law'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#comment'},
    'value': {'type': 'typed-literal',
     'datatype': 'http://www.w3.org/2001/XMLSchema#string',
     'value': 'Summary of case law, treated as a separate bibliographic item.\n\nNote:\n\nTitle of the summary of case law: title furnished by the Court in Canvas, or if not available, type of document (e.g. "Sommaire de l\'Arrêt" or "Sommaire de l\'Ordonnance")'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#subClassOf'},
    'value': {'type': 'uri',
     'value': 'http://publications.europa.eu/ontology/cdm#summary'}},
   {'property': {'type': 'uri',
     'value': 'http://www.w3.org/2000/01/rdf-schema#subClassOf'},
    'value': {'type': 'bnode', 'value': 'nodeID://b57067852'}}]}}