In [5]:
import pandas as pd

## Basic Mode

In [8]:
filename="config_basicMode.txt"

In [9]:
df=pd.read_csv(filename, sep='\t')

In [10]:
df.columns

Index(['CLASS', 'URL', 'QUERY', 'HIERARCHY', 'PROPERTIES', 'OPTION',
       'OPTION_TEXT', 'TYPE', 'CLASSES', 'PARAMETERS', 'FILTERS', 'TOOLTIP',
       'FUNCTION'],
      dtype='object')

In [11]:
df.iloc[0].QUERY

'\n    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> \n    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>\n    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n            SELECT DISTINCT ?opThemeMain ?opThemeMain_uri ?opTheme ?opTheme_uri\n            where {{?opTheme_uri rdf:type ?opThemeMain_uri;\n                       skos:prefLabel ?opTheme.\n                    ?opThemeMain_uri rdfs:label ?opThemeMain\n                    } \n                   filter(?opThemeMain_uri=<http://publications.europa.eu/ontology/cdm#concept_op_theme>)\n                   FILTER(langMatches(lang(?opTheme), "en")).\n                   filter not exists { \n                       ?opTheme_uri skos:broader ?broader\n                   }\n                   }ORDER BY ?opThemeMain ?opTheme\n                   #LIMIT 50\n    '

In [5]:
df

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,opThemeMain,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,opThemeMain-opTheme,opThemeMain-opThemeMain_uri;opTheme-opTheme_uri,PUBLICATIONS - Publications by OP Theme,PUBLICATIONS - Publications by OP Theme,TREE,opThemeMain-Publications Themes;opTheme-OP Theme,NaN,NaN,NaN,NaN
1,Membership,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,membership-person,person-person_uri;person-person_gender;person-...,WHOISWHO Person,WHOISWHO Person,TREE,membership-Membership;person-Person,NaN,NaN,NaN,NaN
2,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-directoryOrg2,directoryOrg2-directoryOrg2_uri;directoryOrg2-...,WHOISWHO directoryOrg second level,WHOISWHO directoryOrg second level,TREE,directoryOrg-Directory Organization;directoryO...,NaN,NaN,NaN,NaN
3,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opTheme-corporateBody,opTheme-opTheme_uri;corporateBody-corporateBod...,OP Themes and publication author,OP Themes and publication author,TREE,opTheme-OP Theme;corporateBody-corporateBody,NaN,NaN,NaN,NaN
4,eurovoc,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovoc-eurovocDomain-eurovocThesauri-eurovocC...,eurovoc-eurovoc_uri;eurovocDomain-eurovocDomai...,"Eurovoc domains, thesauri and concepts",Eurovoc concepts by thesauri and domain,TREE,eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;e...,NaN,NaN,NaN,NaN
5,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX rdfs: <http://www.w3.org/2000/01/rdf-sc...,eurovocConcept-aligment,eurovocConcept-eurovocConcept_uri,Eurovoc concept and aligments,Eurovoc concepts and external aligments,TREE,eurovocConcept-Eurovoc Concept;aligment-Aligment,NaN,NaN,NaN,NaN
6,nuts,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,nuts-nutsLevel0-nutsLevel1-nutsLevel2-nutsLevel3,nutsLevel0-nutsLevel0_uri;nutsLevel1-nutsLevel...,NUTS Tree,NUTS Tree,TREE,nuts-NUTS Classification;nutsLevel0-NUTS Level...,NaN,NaN,NaN,NaN
7,taxonomy,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,taxonomy-taxonomyType-taxonomyLevel1,taxonomy-taxonomy_def;taxonomyType-taxonomyTyp...,Taxonomies,Taxonomies,TREE,taxonomy-Taxonomies Classification;taxonomyTyp...,NaN,NaN,NaN,NaN
8,Taxonomy Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,taxonomyLevel1-taxonomyLevel2,taxonomyLevel1-taxonomyLevel1_uri;taxonomyLeve...,Taxonomy Level Children,Taxonomy Level Children,TREE,taxonomyLevel1-Taxonomy Level;taxonomyLevel2-T...,NaN,NaN,NaN,NaN
9,det,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,det-detLevel1-detLevel2,det-det_uri;detLevel1-detLevel1_uri;detLevel2-...,Digital Europa Thesaurus,Digital Europa Thesaurus,TREE,det-DET;detLevel1-DET Level;detLevel2-DET Level,NaN,NaN,NaN,NaN
10,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovocConcept-workType-work,eurovocConcept-eurovocConcept_uri;workType-wor...,Eurovoc concept and work types,Eurovoc concepts and works by type,TREE,eurovocConcept-Eurovoc Concept;workType-Work T...,NaN,NaN,NaN,NaN
11,DET Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,detLevel2-detLevel3,detLevel2-detLevel2_uri;detLevel3-detLevel3_uri,DET Children Level,DET Children Level,TREE,detLevel2-DET Level;detLevel3-DET Level,NaN,NaN,NaN,NaN
12,DET Level,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,detLevel1-eurovocConcept,detLevel1-detLevel1_uri;eurovocConcept-eurovoc...,DET Level to Eurovoc Concept,DET Level to Eurovoc Concept,TREE,detLevel1-DET Level;eurovocConcept-Eurovoc Con...,NaN,NaN,NaN,NaN
13,Continents,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,continent-continentName-country-language,continent-continent_uri;continentName-continen...,Languages by country and continent,Languages by country and continent,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
14,Continents,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,continent-continentName-country-org,continent-continent_uri;continentName-continen...,Continents countries and organisations,Continents countries and organisations those c...,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
15,org,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,org,org-org_desc;org-org_code;org-org_startDate;or...,Timeline organisations,Timeline organisations,TIMELINE,org-Organisation,NaN,NaN,NaN,NaN
16,eurun,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,eurun-corporateBody,eurun-eurun_uri;eurun-eurun_image;corporateBod...,WHOISWHO EURUN Suborganizations,WHOISWHO EURUN Suborganizations,TREE,eurun-European Union;corporateBody-corporateBody,NaN,corporateBody_country-dropdown;corporateBody_l...,corporateBody_country-Country;corporateBody_lo...,NaN
17,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-directoryOrg,directoryOrg-directoryOrg_uri;directoryOrg-dir...,WHOISWHO Suborganizations,WHOISWHO Suborganizations,TREE,corporateBody-corporateBody;directoryOrg-Direc...,NaN,NaN,NaN,NaN
18,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-membership,membership-membership_directoryOrg,WHOISWHO Membership,WHOISWHO Membership,TREE,directoryOrg-Directory Organization;membership...,NaN,NaN,NaN,NaN
19,Membership Type,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,membership-person,membership-membership_uri;membership-membershi...,WHOISWHO Membership Type,WHOISWHO Membership Type,TREE,membership-Membership Type;person-Person,membership_directoryOrg,NaN,NaN,NaN
20,Person,https://query.wikidata.org/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,person-article,article,WHOISWHO Wikipedia page,WHOISWHO Wikipedia page,WEBPAGE,article-Wikipedia Article,person_id,NaN,NaN,showWikipediaPage
21,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opThemeParent-opThemeChild,opThemeParent-opThemeParent_uri;opThemeChild-o...,OP Themes children,OP Themes children,TREE,opThemeParent-OP Theme;opThemeChild-OP Theme,NaN,NaN,NaN,NaN
22,Publication Document,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,expression-manifestation,expression-expression_uri;manifestation-manife...,Manifestation by Expression,Manifestation by Expression,TREE,expression-Publication Document;manifestation-...,NaN,NaN,manifestation_type-Manifestation Type,NaN
23,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-publicationDocument,corporateBody-corporateBody_uri;publicationDoc...,Publications by CorporateBody,Publications by CorporateBody,TREE,corporateBody-corporateBody;publicationDocumen...,corporateBody_opTheme,NaN,NaN,NaN

In [501]:
#df[:22]

In [97]:
#df=pd.concat([df[22:],df[:22]])

### Eurovoc domains, thesauri and concepts

In [49]:
df=df[df["OPTION"]!="Eurovoc domains, thesauri and concepts"]

In [50]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [51]:
className="eurovoc"

In [52]:
hierarchy="eurovoc-eurovocDomain-eurovocThesauri-eurovocConcept"

In [53]:
properties="eurovoc-eurovoc_uri;eurovocDomain-eurovocDomain_uri;eurovocThesauri-eurovocThesauri_uri;eurovocConcept-eurovocConcept_uri"

In [54]:
option="Eurovoc domains, thesauri and concepts"

In [55]:
option_text="Eurovoc concepts by thesauri and domain"

In [56]:
query="""PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX dcterms: <http://purl.org/dc/terms/>
    PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>
            SELECT DISTINCT ?eurovoc ?eurovoc_uri ?eurovocDomain ?eurovocDomain_uri ?eurovocThesauri ?eurovocThesauri_uri ?eurovocConcept ?eurovocConcept_uri
            where {{?eurovoc_uri dcterms:hasPart ?eurovocThesauri_uri;
                       skos:prefLabel ?eurovoc.
                    ?eurovocThesauri_uri skos:prefLabel ?eurovocThesauri;
                       euvoc:domain ?eurovocDomain_uri.
                    ?eurovocDomain_uri skos:prefLabel ?eurovocDomain.
                    ?eurovocConcept_uri skos:inScheme ?eurovocThesauri_uri;
                             skos:prefLabel ?eurovocConcept.
                    } 
                   filter(?eurovoc_uri=<http://eurovoc.europa.eu/100141>).
                   FILTER(langMatches(lang(?eurovocDomain), "en")) 
                   FILTER(langMatches(lang(?eurovocThesauri), "en"))
                   FILTER(langMatches(lang(?eurovoc), "en"))
                   FILTER(langMatches(lang(?eurovocConcept), "en"))

                   }ORDER BY ?eurovoc ?eurovocDomain ?eurovocThesauri ?eurovocConcept"""

In [57]:
rowType="TREE"

In [58]:
classes="eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;eurovocThesauri-Eurovoc Thesauri;eurovocConcept-Eurovoc Concept"

In [59]:
parameters=""

In [60]:
tooltip=""

In [61]:
filters=""

In [62]:
function=""

In [63]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [64]:
df_record=pd.DataFrame([record])

In [65]:
df_record

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,eurovoc,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovoc-eurovocDomain-eurovocThesauri-eurovocC...,eurovoc-eurovoc_uri;eurovocDomain-eurovocDomai...,"Eurovoc domains, thesauri and concepts",Eurovoc concepts by thesauri and domain,TREE,eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;e...,,,,

In [66]:
df=pd.concat([df,df_record])

In [67]:
#df=df[df["OPTION_TEXT"]!="Eurovoc thesauri by domain"]

In [68]:
df.columns

Index(['CLASS', 'URL', 'QUERY', 'HIERARCHY', 'PROPERTIES', 'OPTION',
       'OPTION_TEXT', 'TYPE', 'CLASSES', 'PARAMETERS', 'FILTERS', 'TOOLTIP',
       'FUNCTION'],
      dtype='object')

### Eurovoc concepts and aligments

In [70]:
#df=df[df["OPTION"]!="Eurovoc concept and aligments"]

In [71]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [72]:
className="Eurovoc Concept"

In [73]:
hierarchy="eurovocConcept-aligment"

In [74]:
properties="eurovocConcept-eurovocConcept_uri"

In [75]:
option="Eurovoc concept and aligments"

In [76]:
option_text="Eurovoc concepts and external aligments"

In [77]:
query="""PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    
SELECT ?eurovocConcept ?eurovocConcept_uri ?aligment WHERE
{
    ?eurovocConcept_uri skos:inScheme <http://eurovoc.europa.eu/100141> ;
    skos:prefLabel ?eurovocConcept
    {?eurovocConcept_uri skos:exactMatch ?aligment}
    UNION
    {?eurovocConcept_uri skos:closeMatch ?aligment}
    #filter (strStarts(str(?aligment), 'https://en.wikipedia.org/')).
    FILTER(langMatches(lang(?eurovocConcept), "en")).
    filter(?eurovocConcept_uri=<PARAMETER>).
}ORDER BY ?eurovocConcept ?aligment"""

In [78]:
rowType="TREE"

In [79]:
classes="eurovocConcept-Eurovoc Concept;aligment-Aligment"

In [80]:
parameters=""

In [81]:
tooltip=""

In [82]:
filters=""

In [83]:
function=""

In [84]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [85]:
df_record=pd.DataFrame([record])

In [86]:
df_record

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX rdfs: <http://www.w3.org/2000/01/rdf-sc...,eurovocConcept-aligment,eurovocConcept-eurovocConcept_uri,Eurovoc concept and aligments,Eurovoc concepts and external aligments,TREE,eurovocConcept-Eurovoc Concept;aligment-Aligment,,,,

In [87]:
df=pd.concat([df,df_record])

In [88]:
#df=df[df["OPTION_TEXT"]!="Eurovoc thesauri by domain"]

In [89]:
df.columns

Index(['CLASS', 'URL', 'QUERY', 'HIERARCHY', 'PROPERTIES', 'OPTION',
       'OPTION_TEXT', 'TYPE', 'CLASSES', 'PARAMETERS', 'FILTERS', 'TOOLTIP',
       'FUNCTION'],
      dtype='object')

### Eurovoc concepts and work types

In [91]:
#df=df[df["OPTION"]!="Eurovoc concept and work types"]

In [306]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [307]:
className="Eurovoc Concept"

In [308]:
hierarchy="eurovocConcept-workType-work"

In [309]:
properties="eurovocConcept-eurovocConcept_uri;workType-workType_uri;work-work_uri"

In [310]:
option="Eurovoc concept and work types"

In [311]:
option_text="Eurovoc concepts and works by type"

In [312]:
query="""PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX purl: <http://purl.org/dc/terms/>
    PREFIX rdfs: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
    PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
            SELECT DISTINCT ?eurovocConcept ?eurovocConcept_uri ?workType ?workType_uri ?work ?work_uri
            where {{?eurovocConcept_uri skos:prefLabel ?eurovocConcept.
                    ?work_uri cdm:work_is_about_concept_eurovoc ?eurovocConcept_uri;
                          rdfs:type ?workType_uri;
                          cdm:work_title ?work.
                    ?workType_uri rdf:label ?workType
                    }
                   FILTER(langMatches(lang(?eurovocConcept), "en")) 
                   FILTER(?eurovocConcept_uri=<PARAMETER>)
                   FILTER (isLiteral(?workType) && lcase(str(?workType)) != "work")
                   }
                   ORDER BY ?eurovocConcept ?workType ?work"""

In [313]:
rowType="TREE"

In [314]:
classes="eurovocConcept-Eurovoc Concept;workType-Work Type;work-Work"

In [315]:
parameters=""

In [316]:
tooltip=""

In [317]:
filters=""

In [318]:
function=""

In [319]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [320]:
df_record=pd.DataFrame([record])

In [321]:
df_record

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovocConcept-workType-work,eurovocConcept-eurovocConcept_uri;workType-wor...,Eurovoc concept and work types,Eurovoc concepts and works by type,TREE,eurovocConcept-Eurovoc Concept;workType-Work T...,,,,

In [322]:
df=pd.concat([df,df_record])

In [109]:
#df=df[df["OPTION_TEXT"]!="Eurovoc concepts and works by type"]

In [110]:
df.columns

Index(['CLASS', 'URL', 'QUERY', 'HIERARCHY', 'PROPERTIES', 'OPTION',
       'OPTION_TEXT', 'TYPE', 'CLASSES', 'PARAMETERS', 'FILTERS', 'TOOLTIP',
       'FUNCTION'],
      dtype='object')

### NUTS Tree

In [112]:
df=df[df["OPTION"]!="NUTS Tree"]

In [113]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [114]:
className="nuts"

In [115]:
hierarchy="nuts-nutsLevel0-nutsLevel1-nutsLevel2-nutsLevel3"

In [116]:
properties="nutsLevel0-nutsLevel0_uri;nutsLevel1-nutsLevel1_uri;nutsLevel2-nutsLevel2_uri;nutsLevel3-nutsLevel3_uri"

In [117]:
option="NUTS Tree"

In [118]:
option_text="NUTS Tree"

In [119]:
query="""PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX dcterms: <http://purl.org/dc/terms/>

    SELECT DISTINCT ?nuts ?nutsLevel0 ?nutsLevel0_uri ?nutsLevel1 ?nutsLevel1_uri ?nutsLevel2 ?nutsLevel2_uri ?nutsLevel3 ?nutsLevel3_uri
    where {{?nutsLevel3_uri ?p ?o;
               skos:prefLabel ?nutsLevel3;
               skos:broader ?nutsLevel2_uri.
            ?nutsLevel2_uri skos:prefLabel ?nutsLevel2;
                             skos:broader ?nutsLevel1_uri.
            ?nutsLevel1_uri skos:prefLabel ?nutsLevel1;
                             skos:broader ?nutsLevel0_uri.
            ?nutsLevel0_uri skos:prefLabel ?nutsLevel0;
                             skos:inScheme <http://data.europa.eu/nuts>.
            <http://data.europa.eu/nuts> skos:prefLabel ?nuts
            } 
           FILTER(?p=<http://data.europa.eu/nuts/level>).
           FILTER(?o=3) 
           }ORDER BY ?nuts ?nutsLevel0 ?nutsLevel1 ?nutsLevel2 ?nutsLevel3"""

In [120]:
rowType="TREE"

In [121]:
classes="nuts-NUTS Classification;nutsLevel0-NUTS Level 0;nutsLevel1-NUTS Level 1;nutsLevel2-NUTS Level 2;;nutsLevel3-NUTS Level 3"

In [122]:
parameters=""

In [123]:
tooltip=""

In [124]:
filters=""

In [125]:
function=""

In [126]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [127]:
df_record=pd.DataFrame([record])

In [128]:
df=pd.concat([df,df_record])

In [129]:
#df=df[df["OPTION_TEXT"]!="NUTS Tree"]

In [130]:
df.columns

Index(['CLASS', 'URL', 'QUERY', 'HIERARCHY', 'PROPERTIES', 'OPTION',
       'OPTION_TEXT', 'TYPE', 'CLASSES', 'PARAMETERS', 'FILTERS', 'TOOLTIP',
       'FUNCTION'],
      dtype='object')

### TAXONOMY

In [157]:
df=df[df["OPTION"]!="Taxonomies"]

In [158]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [159]:
className="taxonomy"

In [160]:
hierarchy="taxonomy-taxonomyType-taxonomyLevel1"

In [161]:
properties="taxonomy-taxonomy_def;taxonomyType-taxonomyType_uri;taxonomyType-taxonomyType_desc;taxonomyLevel1-taxonomyLevel1_uri;taxonomyLevel1-taxonomyLevel1_definition"

In [162]:
option="Taxonomies"

In [163]:
option_text="Taxonomies"

In [164]:
query="""PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX owl: <http://www.w3.org/2002/07/owl#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            SELECT DISTINCT ?taxonomy ?taxonomy_def ?taxonomyType ?taxonomyType_uri ?taxonomyType_desc ?taxonomyLevel1 ?taxonomyLevel1_uri ?taxonomyLevel1_definition
            where {{<http://publications.europa.eu/resource/authority/dataset-type/TAXONOMY> skos:prefLabel ?taxonomy;
                       skos:definition ?taxonomy_def.
                    ?s cdm:work_dataset_has_type_concept_type_dataset <http://publications.europa.eu/resource/authority/dataset-type/TAXONOMY>;
                       cdm:work_id ?taxonomyType_uri;
                       cdm:work_dataset_description_editorial ?taxonomyType_desc;
                       cdm:work_title ?taxonomyType.
                    BIND(IRI(?taxonomyType_uri) as ?idUri)
                    ?idUri skos:hasTopconcept ?taxonomyLevel1_uri.
                    ?taxonomyLevel1_uri skos:prefLabel ?taxonomyLevel1.
                    OPTIONAL {?taxonomyLevel1_uri skos:definition ?taxonomyLevel1_definition }
                    #?idUri skos:prefLabel ?label
                    FILTER(langMatches(lang(?taxonomy), "en")).
                    FILTER(langMatches(lang(?taxonomyLevel1), "en")).
                    #FILTER(langMatches(lang(?label), "en")).
                       }
                   } ORDER BY ?taxonomy ?taxonomyType ?taxonomyLevel1"""

In [165]:
rowType="TREE"

In [166]:
classes="taxonomy-Taxonomies Classification;taxonomyType-Taxonomy Type;taxonomyLevel1-Taxonomy Level"

In [167]:
parameters=""

In [168]:
tooltip=""

In [169]:
filters=""

In [170]:
function=""

In [171]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [172]:
df_record=pd.DataFrame([record])

In [173]:
df_record

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,taxonomy,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,taxonomy-taxonomyType-taxonomyLevel1,taxonomy-taxonomy_def;taxonomyType-taxonomyTyp...,Taxonomies,Taxonomies,TREE,taxonomy-Taxonomies Classification;taxonomyTyp...,,,,

In [174]:
df=pd.concat([df,df_record])

In [175]:
#df=df[df["OPTION_TEXT"]!="Eurovoc concepts and works by type"]

In [176]:
df.columns

Index(['CLASS', 'URL', 'QUERY', 'HIERARCHY', 'PROPERTIES', 'OPTION',
       'OPTION_TEXT', 'TYPE', 'CLASSES', 'PARAMETERS', 'FILTERS', 'TOOLTIP',
       'FUNCTION'],
      dtype='object')

### TAXONOMY Level Children

In [201]:
#df=df[df["OPTION"]!="Taxonomy Level Children"]

In [202]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [203]:
className="Taxonomy Level"

In [204]:
hierarchy="taxonomyLevel1-taxonomyLevel2"

In [205]:
properties="taxonomyLevel1-taxonomyLevel1_uri;taxonomyLevel2-taxonomyLevel2_uri"

In [206]:
option="Taxonomy Level Children"

In [207]:
option_text="Taxonomy Level Children"

In [208]:
query="""PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
            SELECT DISTINCT ?taxonomyLevel1 ?taxonomyLevel1_uri ?taxonomyLevel2 ?taxonomyLevel2_uri
                    WHERE{{
                    ?taxonomyLevel1_uri skos:prefLabel ?taxonomyLevel1;
                                         skos:narrower ?taxonomyLevel2_uri.
                    ?taxonomyLevel2_uri skos:prefLabel ?taxonomyLevel2
                    } 
                   filter(?taxonomyLevel1_uri=<PARAMETER>).
                   FILTER(langMatches(lang(?taxonomyLevel2), "en"))
                   FILTER(langMatches(lang(?taxonomyLevel1), "en"))
                   }ORDER BY ?taxonomyLevel1 ?taxonomyLevel2"""

In [209]:
rowType="TREE"

In [210]:
classes="taxonomyLevel1-Taxonomy Level;taxonomyLevel2-Taxonomy Level"

In [211]:
parameters=""

In [212]:
tooltip=""

In [213]:
filters=""

In [214]:
function=""

In [215]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [216]:
df_record=pd.DataFrame([record])

In [217]:
df=pd.concat([df,df_record])

In [218]:
#df=df[df["OPTION_TEXT"]!="Works for eurovoc concept electronic voting"]

In [219]:
df.columns

Index(['CLASS', 'URL', 'QUERY', 'HIERARCHY', 'PROPERTIES', 'OPTION',
       'OPTION_TEXT', 'TYPE', 'CLASSES', 'PARAMETERS', 'FILTERS', 'TOOLTIP',
       'FUNCTION'],
      dtype='object')

In [228]:
#df=df[df["OPTION"]!="Taxonomy Level 5"]

### Digital Europa Thesaurus DET

In [262]:
#df=df[df["OPTION"]!="Digital Europa Thesaurus"]

In [271]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [272]:
className="det"

In [273]:
hierarchy="det-detLevel1-detLevel2"

In [274]:
properties="det-det_uri;detLevel1-detLevel1_uri;detLevel2-detLevel2_uri"

In [275]:
option="Digital Europa Thesaurus"

In [276]:
option_text="Digital Europa Thesaurus"

In [277]:
query="""PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX owl: <http://www.w3.org/2002/07/owl#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            SELECT DISTINCT ?det ?det_uri ?detLevel1 ?detLevel1_uri ?detLevel2 ?detLevel2_uri
            where {{ ?det_uri skos:prefLabel ?det;
                               skos:hasTopConcept ?detLevel1_uri.
                    ?detLevel1_uri skos:prefLabel ?detLevel1;
                               skos:narrower ?detLevel2_uri.
                    ?detLevel2_uri skos:prefLabel ?detLevel2.
                    FILTER(langMatches(lang(?detLevel1), "en")).
                    FILTER(langMatches(lang(?detLevel2), "en")).
                    #FILTER(langMatches(lang(?taxonomyLevel1), "en")).
                    #FILTER(langMatches(lang(?label), "en")).
                    FILTER(?det_uri=<http://data.europa.eu/uxp/det>)
                       }
                   } ORDER BY ?det ?det ?detLevel1"""

In [278]:
classes="det-DET;detLevel1-DET Level;detLevel2-DET Level"

In [279]:
parameters=""

In [280]:
tooltip=""

In [281]:
filters=""

In [282]:
function=""

In [283]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [284]:
df_record=pd.DataFrame([record])

In [285]:
df=pd.concat([df,df_record])

In [431]:
#df=df[df["OPTION_TEXT"]!="Eurovoc concepts and works by type"]

### DET Children Level

In [345]:
df=df[df["OPTION_TEXT"]!="DET Level 2"]

In [367]:
df

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,eurun,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,eurun-corporateBody,eurun-eurun_uri;eurun-eurun_image;corporateBod...,WHOISWHO EURUN Suborganizations,WHOISWHO EURUN Suborganizations,TREE,eurun-European Union;corporateBody-corporateBody,NaN,corporateBody_country-dropdown;corporateBody_l...,corporateBody_country-Country;corporateBody_lo...,NaN
1,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-directoryOrg,directoryOrg-directoryOrg_uri;directoryOrg-dir...,WHOISWHO Suborganizations,WHOISWHO Suborganizations,TREE,corporateBody-corporateBody;directoryOrg-Direc...,NaN,NaN,NaN,NaN
2,Membership,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,membership-person,person-person_uri;person-person_gender;person-...,WHOISWHO Person,WHOISWHO Person,TREE,membership-Membership;person-Person,NaN,NaN,NaN,NaN
3,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-directoryOrg2,directoryOrg2-directoryOrg2_uri;directoryOrg2-...,WHOISWHO directoryOrg second level,WHOISWHO directoryOrg second level,TREE,directoryOrg-Directory Organization;directoryO...,NaN,NaN,NaN,NaN
4,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-membership,membership-membership_directoryOrg,WHOISWHO Membership,WHOISWHO Membership,TREE,directoryOrg-Directory Organization;membership...,NaN,NaN,NaN,NaN
5,Membership Type,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,membership-person,membership-membership_uri;membership-membershi...,WHOISWHO Membership Type,WHOISWHO Membership Type,TREE,membership-Membership Type;person-Person,membership_directoryOrg,NaN,NaN,NaN
6,opThemeMain,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,opThemeMain-opTheme,opThemeMain-opThemeMain_uri;opTheme-opTheme_uri,PUBLICATIONS - Publications by OP Theme,PUBLICATIONS - Publications by OP Theme,TREE,opThemeMain-Publications Themes;opTheme-OP Theme,NaN,NaN,NaN,NaN
23,continent,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,continent-continentName-country,continent-continent_uri;continentName-continen...,Countries by continent,Countries by continent,TREE,NaN,NaN,NaN,NaN,NaN
24,continent,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,continent-continentName-country-language,continent-continent_uri;continentName-continen...,Languages by country and continent,Languages by country and continent,TREE,NaN,NaN,NaN,NaN,NaN
25,continent,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,continent-continentName-country-org,continent-continent_uri;continentName-continen...,Continents countries and organisations,Continents countries and organisations those c...,TREE,NaN,NaN,NaN,NaN,NaN
26,org,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,org,org-org_desc;org-org_code;org-org_startDate;or...,Timeline organisations,Timeline organisations,TIMELINE,NaN,NaN,NaN,NaN,NaN
27,orgTypeMain,https://publications.europa.eu/webapi/rdf/sparql,PREFIX authority: <http://publications.europa....,orgTypeMain-orgType-directoryOrg,orgTypeMain-orgTypeMain_uri;orgType-orgType_ur...,WHOISWHO Organisations types,WHOISWHO Organisations types,TREE,NaN,NaN,NaN,NaN,NaN
28,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opTheme-corporateBody,opTheme-opTheme_uri;corporateBody-corporateBod...,OP Themes and publication author,OP Themes and publication author,TREE,opTheme-OP Theme;corporateBody-corporateBody,NaN,NaN,NaN,NaN
29,Publication Expression,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,expression-manifestation,expression-expression_uri;manifestation-manife...,Manifestation by Expression,Manifestation by Expression,TREE,expression-Publication Expression;manifestatio...,NaN,NaN,NaN,NaN
30,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opThemeParent-opThemeChild,opThemeParent-opThemeParent_uri;opThemeChild-o...,OP Themes children,OP Themes children,TREE,opThemeParent-OP Theme;opThemeChild-OP Theme,NaN,NaN,NaN,NaN
31,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-expression,corporateBody-corporateBody_uri;expression-exp...,Publications by CorporateBody,Publications by CorporateBody,TREE,corporateBody-corporateBody;expression-Publica...,corporateBody_opTheme,NaN,NaN,NaN
32,Publication Document,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,expression-manifestation,expression-expression_uri;manifestation-manife...,Manifestation by Expression,Manifestation by Expression,TREE,expression-Publication Document;manifestation-...,NaN,NaN,NaN,NaN
33,Person,https://query.wikidata.org/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,person-article,article,WHOISWHO Wikipedia page,WHOISWHO Wikipedia page,WEBPAGE,article-Wikipedia Article,person_id,NaN,NaN,showWikipediaPage
0,eurovoc,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovoc-eurovocDomain-eurovocThesauri-eurovocC...,eurovoc-eurovoc_uri;eurovocDomain-eurovocDomai...,"Eurovoc domains, thesauri and concepts",Eurovoc concepts by thesauri and domain,TREE,eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;e...,,,,
0,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX rdfs: <http://www.w3.org/2000/01/rdf-sc...,eurovocConcept-aligment,eurovocConcept-eurovocConcept_uri,Eurovoc concept and aligments,Eurovoc concepts and external aligments,TREE,eurovocConcept-Eurovoc Concept;aligment-Aligment,,,,
0,nuts,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,nuts-nutsLevel0-nutsLevel1-nutsLevel2-nutsLevel3,nutsLevel0-nutsLevel0_uri;nutsLevel1-nutsLevel...,NUTS Tree,NUTS Tree,TREE,nuts-NUTS Classification;nutsLevel0-NUTS Level...,,,,
0,taxonomy,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,taxonomy-taxonomyType-taxonomyLevel1,taxonomy-taxonomy_def;taxonomyType-taxonomyTyp...,Taxonomies,Taxonomies,TREE,taxonomy-Taxonomies Classification;taxonomyTyp...,,,,
0,Taxonomy Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,taxonomyLevel1-taxonomyLevel2,taxonomyLevel1-taxonomyLevel1_uri;taxonomyLeve...,Taxonomy Level Children,Taxonomy Level Children,TREE,taxonomyLevel1-Taxonomy Level;taxonomyLevel2-T...,,,,
0,det,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,det-detLevel1-detLevel2,det-det_uri;detLevel1-detLevel1_uri;detLevel2-...,Digital Europa Thesaurus,Digital Europa Thesaurus,TREE,det-DET;detLevel1-DET Level;detLevel2-DET Level,,,,
0,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovocConcept-workType-work,eurovocConcept-eurovocConcept_uri;workType-wor...,Eurovoc concept and work types,Eurovoc concepts and works by type,TREE,eurovocConcept-Eurovoc Concept;workType-Work T...,,,,
0,DET Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,detLevel2-detLevel3,detLevel2-detLevel2_uri;detLevel3-detLevel3_uri,DET Children Level,DET Children Level,TREE,detLevel2-DET Level;detLevel3-DET Level,,,,
0,DET Level,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,detLevel1-eurovocConcept,detLevel1-detLevel1_uri;eurovocConcept-eurovoc...,DET Level to Eurovoc Concept,DET Level to Eurovoc Concept,TREE,detLevel1-DET Level;eurovocConcept-Eurovoc Con...,,,,

In [325]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [326]:
className="DET Level"

In [327]:
hierarchy="detLevel2-detLevel3"

In [328]:
properties="detLevel2-detLevel2_uri;detLevel3-detLevel3_uri"

In [329]:
option="DET Children Level"

In [330]:
option_text="DET Children Level"

In [331]:
query="""PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
            SELECT DISTINCT ?detLevel2 ?detLevel2_uri ?detLevel3 ?detLevel3_uri
                    WHERE{{
                    ?detLevel2_uri skos:prefLabel ?detLevel2;
                                         skos:narrower ?detLevel3_uri.
                    ?detLevel3_uri skos:prefLabel ?detLevel3
                    } 
                   filter(?detLevel2_uri=<PARAMETER>).
                   FILTER(langMatches(lang(?detLevel2), "en"))
                   FILTER(langMatches(lang(?detLevel3), "en"))
                   }ORDER BY ?detLevel2 ?detLevel3"""

In [332]:
classes="detLevel2-DET Level;detLevel3-DET Level"

In [333]:
parameters=""

In [334]:
tooltip=""

In [335]:
filters=""

In [336]:
function=""

In [337]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [338]:
df_record=pd.DataFrame([record])

In [339]:
df=pd.concat([df,df_record])

In [451]:
#df=df[df["OPTION_TEXT"]!="Eurovoc concepts and works by type"]

### DET Level TO eurovocConcept

In [348]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [349]:
className="DET Level"

In [350]:
hierarchy="detLevel1-eurovocConcept"

In [351]:
properties="detLevel1-detLevel1_uri;eurovocConcept-eurovocConcept_uri"

In [352]:
option="DET Level to Eurovoc Concept"

In [353]:
option_text="DET Level to Eurovoc Concept"

In [354]:
query="""
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
            SELECT DISTINCT ?detLevel1 ?detLevel1_uri ?eurovocConcept ?eurovocConcept_uri
            where {{?detLevel1_uri skos:prefLabel ?detLevel1;
                                    skos:exactMatch ?eurovocConcept_uri.
                    ?eurovocConcept_uri skos:prefLabel ?eurovocConcept} 
                   filter(?detLevel1_uri=<PARAMETER>).
                   FILTER(langMatches(lang(?detLevel1), "en")).
                   FILTER(langMatches(lang(?eurovocConcept), "en")).
                   }
    """

In [355]:
classes="detLevel1-DET Level;eurovocConcept-Eurovoc Concept"

In [356]:
parameters=""

In [357]:
tooltip=""

In [358]:
filters=""

In [359]:
function=""

In [360]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [361]:
df_record=pd.DataFrame([record])

In [362]:
df=pd.concat([df,df_record])

In [528]:
#df=df[df["OPTION_TEXT"]!="Eurovoc concepts and works by type"]

### Languages by country and continent

In [369]:
#df=df[df["OPTION_TEXT"]!="Languages by country and continent"]

In [377]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [378]:
className="Continents"

In [379]:
hierarchy="continent-continentName-country-language"

In [380]:
properties="continent-continent_uri;continentName-continentName_uri;country-country_uri;language-language_uri"

In [381]:
option="Languages by country and continent"

In [382]:
option_text="Languages by country and continent"

In [383]:
query="""
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
            PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            PREFIX dcterms: <http://purl.org/dc/terms/>
            PREFIX geo: <http://www.opengis.net/ont/geosparql#>
            PREFIX authority: <http://publications.europa.eu/ontology/authority/>
                    SELECT DISTINCT ?continent ?continent_uri ?continentName ?continentName_uri ?country ?country_uri ?language ?language_uri 
                    where {{?continentName_uri skos:prefLabel ?continentName;
                               skos:inScheme ?continent_uri.
                            ?continent_uri skos:prefLabel ?continent.
                            ?country_uri geo:sfWithin ?continentName_uri;
                                         skos:prefLabel ?country;
                                         authority:deprecated ?deprecated;
                                         dcterms:language ?language_uri.
                            ?language_uri skos:prefLabel ?language
                            } 
                           filter(?continent_uri=<http://publications.europa.eu/resource/authority/continent>).
                           FILTER(langMatches(lang(?continent), "en")).
                           FILTER(langMatches(lang(?continentName), "en")).
                           FILTER(langMatches(lang(?country), "en")).
                           filter(?deprecated="false").
                           FILTER(langMatches(lang(?language), "en")).
                           }ORDER BY ?continent ?continentName ?country ?language
    """

In [385]:
classes="continent-Continents;continentName-Continent;country-Country;language-Language"

In [386]:
parameters=""

In [387]:
tooltip=""

In [388]:
filters=""

In [389]:
function=""

In [390]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [391]:
df_record=pd.DataFrame([record])

In [392]:
df=pd.concat([df,df_record])

### Continent, country and organisations

In [403]:
#df=df[df["OPTION_TEXT"]!="Continents countries and organisations"]

In [404]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [405]:
className="Continents"

In [406]:
hierarchy="continent-continentName-country-org"

In [407]:
properties="continent-continent_uri;continentName-continentName_uri;country-country_uri;org-org_desc;org-org_code"

In [408]:
option="Continents countries and organisations"

In [409]:
option_text="Continents countries and organisations those countries belong to"

In [410]:
query="""PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
            PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            PREFIX dcterms: <http://purl.org/dc/terms/>
            PREFIX geo: <http://www.opengis.net/ont/geosparql#>
            PREFIX authority: <http://publications.europa.eu/ontology/authority/>
            PREFIX org: <http://www.w3.org/ns/org#>
                    SELECT DISTINCT ?continent ?continent_uri ?continentName ?continentName_uri ?country_uri ?country ?org ?org_code ?org_desc
                    where {{?continentName_uri skos:prefLabel ?continentName;
                               skos:inScheme ?continent_uri.
                            ?continent_uri skos:prefLabel ?continent.
                            ?country_uri geo:sfWithin ?continentName_uri;
                                         skos:prefLabel ?country;
                                         authority:deprecated ?deprecated.
                            OPTIONAL {
                                    ?country_uri org:hasMembership ?o.
                                    ?o org:organization ?org_code.
                                    ?org_code authority:deprecated ?deprecated2;
                                              authority:authority-code ?org;
                                              skos:prefLabel ?org_desc.
                                    filter(?deprecated2="false").
                                    FILTER(langMatches(lang(?org_desc), "en")).
                            }
                            } 
                           filter(?continent_uri=<http://publications.europa.eu/resource/authority/continent>).
                           FILTER(langMatches(lang(?continent), "en")).
                           FILTER(langMatches(lang(?continentName), "en")).
                           FILTER(langMatches(lang(?country), "en")).
                           filter(?deprecated="false").
                           }ORDER BY ?continent ?continentName ?country ?org"""

In [411]:
classes="continent-Continents;continentName-Continent;country-Country;org-Organisation"

In [412]:
parameters=""

In [413]:
tooltip=""

In [414]:
filters=""

In [415]:
function=""

In [416]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [417]:
df_record=pd.DataFrame([record])

In [418]:
df=pd.concat([df,df_record])

### Timeline european organisations

In [421]:
#df=df[df["OPTION_TEXT"]!="Timeline organisations"]

In [422]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [423]:
className="org"

In [424]:
hierarchy="org"

In [425]:
properties="org-org_desc;org-org_code;org-org_startDate;org-org_endDate"

In [426]:
option="Timeline organisations"

In [427]:
option_text="Timeline organisations"

In [428]:
query="""PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
            PREFIX dcterms: <http://purl.org/dc/terms/>
            PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>
            PREFIX authority: <http://publications.europa.eu/ontology/authority/>
                    SELECT DISTINCT ?org ?org_code ?org_desc ?treaty ?startDate ?endDate ?replaces
                    where {{?org_code skos:prefLabel ?org_desc;
                                      authority:authority-code ?org;
                                      euvoc:startDate ?startDate.
                            OPTIONAL {
                            ?org_code euvoc:endDate ?endDate.
                            }
                            OPTIONAL{
                            ?org_code euvoc:legallyBasedOnTreaty ?treaty_code.
                            ?treaty_code skos:prefLabel ?treaty.
                            FILTER(langMatches(lang(?treaty), "en")).
                            }
                            OPTIONAL{
                            ?org_code dcterms:replaces ?replaces.
                            }
                            } 
                           filter(?org_code=<PARAMETER>).
                           FILTER(langMatches(lang(?org_desc), "en")).
                           }"""

In [429]:
rowType="TIMELINE"

In [430]:
classes="org-Organisation"

In [431]:
parameters=""

In [432]:
tooltip=""

In [433]:
filters=""

In [434]:
function=""

In [435]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [436]:
df_record=pd.DataFrame([record])

In [437]:
df=pd.concat([df,df_record])

### WHO IS WHO - EURUN SUBORGANIZATIONS country as property

In [458]:
#df=df[df["OPTION"]!="WHOISWHO EURUN Suborganizations"]

In [459]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [460]:
className="eurun"

In [461]:
hierarchy="eurun-corporateBody"

In [462]:
classes="eurun-European Union;corporateBody-corporateBody"

In [463]:
properties="eurun-eurun_uri;eurun-eurun_image;corporateBody-corporateBody_uri;corporateBody-corporateBody_image;corporateBody-corporateBody_countryUri;corporateBody-corporateBody_country;corporateBody-corporateBody_locationUri;corporateBody-corporateBody_location"

In [464]:
tooltip="corporateBody_country-Country;corporateBody_location-Location"

In [465]:
filters="corporateBody_country-dropdown;corporateBody_location-dropdown"

In [466]:
option="WHOISWHO EURUN Suborganizations"

In [467]:
option_text="WHOISWHO EURUN Suborganizations"

In [468]:
query="""
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX org: <http://www.w3.org/ns/org#>
    PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
    PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            SELECT DISTINCT ?eurun ?eurun_uri ?eurun_image ?corporateBody ?corporateBody_uri ?corporateBody_image ?corporateBody_country ?corporateBody_countryUri ?corporateBody_location ?corporateBody_locationUri   
            where {{?eurun_uri org:hasSubOrganization ?corporateBody_uri;
                           skos:prefLabel ?eurun;
                           foaf:depiction ?eurun_image.
                    ?corporateBody_uri skos:prefLabel ?corporateBody;
                       foaf:depiction ?corporateBody_image;
                       geo:location ?corporateBody_locationUri.
                    ?corporateBody_locationUri skos:prefLabel ?corporateBody_location;
                              geosparql:sfWithin ?corporateBody_countryUri.
                    ?corporateBody_countryUri skos:prefLabel ?corporateBody_country          
                    } 
                   filter(?eurun_uri=<http://publications.europa.eu/resource/authority/corporate-body/EURUN>).
                   FILTER(langMatches(lang(?eurun), "en")).
                   FILTER(langMatches(lang(?corporateBody), "en")).
                   FILTER(langMatches(lang(?corporateBody_location), "en")).
                   FILTER(langMatches(lang(?corporateBody_country), "en")).
                   }ORDER BY ?eurun ?corporateBody
                   #LIMIT 50
    """

In [469]:
rowType="TREE"

In [470]:
parameters=""

In [471]:
function=""

In [472]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [473]:
df_record=pd.DataFrame([record])

In [474]:
df=pd.concat([df,df_record])

### WHO IS WHO - ORGANIZATIONS SUBORGANIZATIONS country as property

In [477]:
#df=df[df["OPTION"]!="WHOISWHO Suborganizations"]

In [478]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [479]:
className="corporateBody"

In [480]:
hierarchy="corporateBody-directoryOrg"

In [481]:
properties="directoryOrg-directoryOrg_uri;directoryOrg-directoryOrg_order;directoryOrg-directoryOrg_protocolLevel;directoryOrg-directoryOrg_email;directoryOrg-directoryOrg_telephone;directoryOrg-directoryOrg_locality;directoryOrg-directoryOrg_postalCode;directoryOrg-directoryOrg_streetAddress;directoryOrg-directoryOrg_homepage"

In [482]:
option="WHOISWHO Suborganizations"

In [483]:
option_text="WHOISWHO Suborganizations"

In [484]:
query="""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX org: <http://www.w3.org/ns/org#>
    PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
    PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>
    PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
            SELECT DISTINCT ?corporateBody ?directoryOrg ?directoryOrg_uri ?directoryOrg_order ?directoryOrg_protocolLevel ?directoryOrg_email ?directoryOrg_telephone ?directoryOrg_locality ?directoryOrg_postalCode ?directoryOrg_streetAddress ?directoryOrg_homepage
            where {{?corporateBody_uri skos:prefLabel ?corporateBody.
                    ?corporateBody_uri org:hasSubOrganization ?directoryOrg_uri. 
                    ?directoryOrg_uri skos:prefLabel ?directoryOrg.
                    OPTIONAL {
                    ?directoryOrg_uri euvoc:order ?directoryOrg_order.
                    }
                    OPTIONAL {
                    ?directoryOrg_uri euvoc:protocolLevel ?directoryOrg_protocolLevel.
                    }
                    #OPTIONAL {
                    #?directoryOrg_uri euvoc:contactPoint ?directoryOrg_contactPoint.
                    #}
                    #OPTIONAL {
                    #?directoryOrg_contactPoint vcard:hasEmail ?directoryOrg_email.
                    #}
                    #OPTIONAL {
                    #?directoryOrg_contactPoint vcard:hasTelephone ?directoryOrg_telephoneBN.
                    #}
                    #OPTIONAL {
                    #?directoryOrg_contactPoint vcard:locality ?directoryOrg_locality.
                    #}
                    #OPTIONAL {
                    #?directoryOrg_contactPoint vcard:postal-code ?directoryOrg_postalCode.
                    #}
                    #OPTIONAL {
                    #?directoryOrg_contactPoint vcard:street-address ?directoryOrg_streetAddress.
                    #}
                    #OPTIONAL {
                    #?directoryOrg_contactPoint foaf:homepage ?directoryOrg_homepage.
                    #}
                    #OPTIONAL {
                    #?directoryOrg_telephoneBN vcard:hasValue ?directoryOrg_telephone.  
                    #}
                    } 
                   filter(?corporateBody_uri=<PARAMETER>).
                   FILTER(langMatches(lang(?directoryOrg), "en")).
                   FILTER(langMatches(lang(?corporateBody), "en")).
                   }
                   #ORDER BY ?whoiswhoOrg ?country ?location
                   #LIMIT 50
    """

In [485]:
rowType="TREE"

In [486]:
classes="corporateBody-corporateBody;directoryOrg-Directory Organization"

In [487]:
parameters=""

In [488]:
tooltip=""

In [489]:
filters=""

In [490]:
function=""

In [491]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [492]:
df_record=pd.DataFrame([record])

In [493]:
df=pd.concat([df,df_record])

In [171]:
#df=df[df["OPTION"]!="WHOISWHO Suborganizations"]

### WHO IS WHO - Membership type in organization

In [502]:
#df=df[df["OPTION"]!="WHOISWHO Membership"]

In [503]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [504]:
className="Directory Organization"

In [505]:
hierarchy="directoryOrg-membership"

In [506]:
properties="membership-membership_directoryOrg"

In [507]:
option="WHOISWHO Membership"

In [508]:
option_text="WHOISWHO Membership"

In [509]:
query="""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX org: <http://www.w3.org/ns/org#>
    PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>
            SELECT DISTINCT ?directoryOrg ?membership ?directoryOrg_uri AS ?membership_directoryOrg
            where {{?membership_uri org:organization ?directoryOrg_uri;
                                    euvoc:order ?membership_order;
                                    euvoc:positionComplement ?membership.
                    ?directoryOrg_uri skos:prefLabel ?directoryOrg.
                    } 
                   filter(?directoryOrg_uri=<PARAMETER>).
                   FILTER(langMatches(lang(?membership), "en")).
                   FILTER(langMatches(lang(?directoryOrg), "en")).
                   }GROUP BY ?membership
    """

In [510]:
rowType="TREE"

In [511]:
classes="directoryOrg-Directory Organization;membership-Membership Type"

In [512]:
parameters=""

In [513]:
tooltip=""

In [514]:
filters=""

In [515]:
function=""

In [516]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [517]:
df_record=pd.DataFrame([record])

In [518]:
df=pd.concat([df,df_record])

### WHO IS WHO - Membership by membership type

In [520]:
#df=df[df["OPTION"]!="WHOISWHO Membership Type"]

In [198]:
#df["PARAMETERS"]=""

In [521]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [522]:
className="Membership Type"

In [523]:
hierarchy="membership-person"

In [524]:
classes="membership-Membership Type;person-Person"

In [525]:
properties="membership-membership_uri;membership-membership_startDate;membership-membership_endDate;membership-membership_order;membership-membership_positionStatusUri;membership-membership_positionStatus;person-person_uri;person-person_gender;person-person_genderUri;person-person_citiz;person-person_image;person-person_id"

In [526]:
parameters="membership_directoryOrg"

In [527]:
option="WHOISWHO Membership Type"

In [528]:
option_text="WHOISWHO Membership Type"

In [529]:
query="""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX org: <http://www.w3.org/ns/org#>
    PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    PREFIX resource: <http://publications.europa.eu/resource/>
            SELECT DISTINCT ?membership ?membership_uri ?membership_startDate ?membership_endDate ?membership_order ?membership_positionStatusUri ?membership_positionStatus ?person ?person_uri ?person_id ?person_image ?person_citiz ?person_gender ?person_genderUri
            where {{?membership_uri org:organization ?directoryOrg_uri;
                       euvoc:startDate ?membership_startDate;
                       euvoc:endDate ?membership_endDate;
                       euvoc:order ?membership_order;
                       euvoc:positionComplement ?membership;
                       euvoc:positionStatus ?membership_positionStatusUri.
                       #euvoc:roleQualification ?roleQualification_uri;
                       #euvoc:contactPoint ?contactPoint.
                    ?directoryOrg_uri skos:prefLabel ?directoryOrg.
                    ?membership_positionStatusUri skos:prefLabel ?membership_positionStatus.
                    ?person_uri org:hasMembership ?membership_uri;
                    #            vcard:hasGender ?person_genderUri;
                                foaf:name ?person.
                    #?person_genderUri skos:prefLabel ?person_gender.
                    OPTIONAL{
                        ?person_uri foaf:img ?person_image;
                                    resource:personcitizenship ?person_citizUri.
                        ?person_citizUri skos:prefLabel ?person_citiz.
                        FILTER(langMatches(lang(?person_citiz), "en")).
                        BIND (STRBEFORE(STRAFTER( STR(?person_image), "https://www.europarl.europa.eu/mepphoto/" ), ".jpg" ) AS ?person_id)
                        #BIND (regex(STR(?person_img), "^https", "i") AS ?str_event)
                    }
                    } 
                   FILTER(STR(?membership)="PARAMETER").
                   filter(?directoryOrg_uri=<PARAMETER2>).
                   FILTER(langMatches(lang(?membership), "en")).
                   FILTER(langMatches(lang(?membership_positionStatus), "en")).
                   FILTER(langMatches(lang(?directoryOrg), "en")).
                   #FILTER(langMatches(lang(?person_gender), "en")).
                   }ORDER BY ?membership_order ?person
"""

In [530]:
rowType="TREE"

In [531]:
tooltip=""

In [532]:
filters=""

In [533]:
function=""

In [534]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [535]:
df_record=pd.DataFrame([record])

In [536]:
df=pd.concat([df,df_record])

### WHO IS WHO - Wikipedia page person

In [539]:
#df=df[df["OPTION"]!="WHOISWHO Wikipedia page"]

In [540]:
url="https://query.wikidata.org/sparql"

In [541]:
className="Person"

In [542]:
hierarchy="person-article"

In [543]:
classes="article-Wikipedia Article"

In [544]:
parameters="person_id"

In [545]:
properties="article"

In [546]:
option="WHOISWHO Wikipedia page"

In [547]:
option_text="WHOISWHO Wikipedia page"

In [548]:
function="showWikipediaPage"

In [549]:
query="""
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX org: <http://www.w3.org/ns/org#>
            SELECT DISTINCT ?s ?article #?label
            where {{?s <http://www.wikidata.org/prop/direct/P1186> 'PARAMETER2'.
                    ?article schema:about ?s .
                    ?article schema:inLanguage "en" .
                    ?article schema:isPartOf <https://en.wikipedia.org/> .
                    } 
                   }
    """

In [550]:
rowType="WEBPAGE"

In [551]:
tooltip=""

In [552]:
filters=""

In [553]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [554]:
df_record=pd.DataFrame([record])

In [555]:
df=pd.concat([df,df_record])

In [47]:
#df=df[df["CLASS"]!="directoryOrg2"]

In [43]:
#df.loc[36, 'CLASS'] = "Directory Organization"
#df.loc[36, 'CLASS'] = "Membership"
#df.loc[36, 'HIERARCHY'] = "membership-person"
#df.loc[36, 'CLASS'] = "European Union"

### PUBLICATIONS - Publications by OP Theme

In [558]:
#df=df[df["OPTION"]!="PUBLICATIONS - Publications by OP Theme"]

In [559]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [560]:
className="opThemeMain"

In [561]:
hierarchy="opThemeMain-opTheme"

In [562]:
classes="opThemeMain-Publications Themes;opTheme-OP Theme"

In [563]:
properties="opThemeMain-opThemeMain_uri;opTheme-opTheme_uri"

In [564]:
option="PUBLICATIONS - Publications by OP Theme"

In [565]:
option_text="PUBLICATIONS - Publications by OP Theme"

In [566]:
query="""
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
            SELECT DISTINCT ?opThemeMain ?opThemeMain_uri ?opTheme ?opTheme_uri
            where {{?opTheme_uri rdf:type ?opThemeMain_uri;
                       skos:prefLabel ?opTheme.
                    ?opThemeMain_uri rdfs:label ?opThemeMain
                    } 
                   filter(?opThemeMain_uri=<http://publications.europa.eu/ontology/cdm#concept_op_theme>)
                   FILTER(langMatches(lang(?opTheme), "en")).
                   filter not exists { 
                       ?opTheme_uri skos:broader ?broader
                   }
                   }ORDER BY ?opThemeMain ?opTheme
                   #LIMIT 50
    """

In [567]:
rowType="TREE"

In [568]:
parameters=""

In [569]:
tooltip=""

In [570]:
filters=""

In [571]:
function=""

In [572]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [573]:
df_record=pd.DataFrame([record])

In [574]:
df=pd.concat([df,df_record])

### PUBLICATIONS - OP Themes children of OP Theme

In [578]:
#df=df[df["OPTION"]!="OP Themes children"]

In [579]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [580]:
className="OP Theme"

In [581]:
hierarchy="opThemeParent-opThemeChild"

In [582]:
classes="opThemeParent-OP Theme;opThemeChild-OP Theme"

In [583]:
properties="opThemeParent-opThemeParent_uri;opThemeChild-opThemeChild_uri"

In [584]:
option="OP Themes children"

In [585]:
option_text="OP Themes children"

In [586]:
query="""
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
        PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
        PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
        SELECT DISTINCT ?opThemeParent ?opThemeParent_uri ?opThemeChild ?opThemeChild_uri
        where {{?opThemeChild_uri skos:broader ?opThemeParent_uri;
                   skos:prefLabel ?opThemeChild.
                ?opThemeParent_uri skos:prefLabel ?opThemeParent.
                } 
               filter(?opThemeParent_uri=<PARAMETER>)
               FILTER(langMatches(lang(?opThemeParent), "en")).
               FILTER(langMatches(lang(?opThemeChild), "en")).
               }ORDER BY ?opThemeParent ?opThemeChild
    """

In [587]:
rowType="TREE"

In [588]:
parameters=""

In [589]:
tooltip=""

In [590]:
filters=""

In [591]:
function=""

In [592]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [593]:
df_record=pd.DataFrame([record])

In [594]:
df=pd.concat([df,df_record])

### PUBLICATIONS - OP Themes and Agents authored work

In [218]:
df=df[df["OPTION"]!="OP Themes and publication author"]

In [219]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [220]:
className="OP Theme"

In [221]:
hierarchy="opTheme-corporateBody"

In [222]:
classes="opTheme-OP Theme;corporateBody-corporateBody"

In [223]:
properties="opTheme-opTheme_uri;corporateBody-corporateBody_uri;corporateBody-corporateBody_opTheme"

In [224]:
option="OP Themes and publication author"

In [225]:
option_text="OP Themes and publication author"

In [226]:
query="""
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
        PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
        PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
                SELECT DISTINCT ?opTheme ?opTheme_uri ?corporateBody ?corporateBody_uri ?opTheme_uri AS ?corporateBody_opTheme
                where {{?publicationDocument_uri cdm:publication_general_is_about_concept_op_theme ?opTheme_uri;
                           cdm:work_authored_by_agent ?corporateBody_uri.
                        ?opTheme_uri skos:prefLabel ?opTheme.
                        ?corporateBody_uri skos:prefLabel ?corporateBody.
                        } 
                       filter(?opTheme_uri=<PARAMETER>)
                       FILTER(langMatches(lang(?corporateBody), "en")).
                       FILTER(langMatches(lang(?opTheme), "en")).
                       }ORDER BY ?opTheme ?corporateBody
    """

In [227]:
rowType="TREE"

In [487]:
parameters=""

In [488]:
tooltip=""

In [489]:
filters=""

In [490]:
function=""

In [491]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [229]:
df_record=pd.DataFrame([record])

In [230]:
df=pd.concat([df,df_record])

### Publications by Corporate Body

In [50]:
#df=df[df["OPTION"]!="Publications by CorporateBody"]

In [51]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [52]:
className="corporateBody"

In [53]:
hierarchy="corporateBody-publicationDocument"

In [54]:
classes="corporateBody-corporateBody;publicationDocument-Publication Document"

In [55]:
properties="corporateBody-corporateBody_uri;publicationDocument-publicationDocument_uri;publicationDocument-publicationDocument_date"

In [56]:
option="Publications by CorporateBody"

In [57]:
option_text="Publications by CorporateBody"

In [58]:
parameters="corporateBody_opTheme"

In [59]:
query="""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            SELECT DISTINCT ?corporateBody ?corporateBody_uri ?publicationDocument ?publicationDocument_uri ?publicationDocument_documentUri ?publicationDocument_date
            where {{?publicationDocument_documentUri cdm:publication_general_is_about_concept_op_theme ?opTheme_uri;
                       cdm:work_authored_by_agent ?corporateBody_uri.
                    ?opTheme_uri skos:prefLabel ?opTheme.
                    ?corporateBody_uri skos:prefLabel ?corporateBody.
                    ?publicationDocument_documentUri cdm:work_date_document ?publicationDocument_date.
                    ?publicationDocument_uri cdm:expression_belongs_to_work ?publicationDocument_documentUri;
                       cdm:expression_uses_language ?expression_languageUri;
                       cdm:expression_title ?publicationDocument.
                    ?expression_languageUri skos:prefLabel ?expression_language.
                    } 
                   filter(?opTheme_uri=<PARAMETER2>)
                   filter(?corporateBody_uri=<PARAMETER>)
                   FILTER(langMatches(lang(?corporateBody), "en")).
                   FILTER(langMatches(lang(?opTheme), "en")).
                   FILTER(langMatches(lang(?expression_language), "en")).
                   }ORDER BY ?corporateBody ?publicationDocument
    """

In [60]:
rowType="TREE"

In [61]:
tooltip=""

In [62]:
filters=""

In [63]:
function=""

In [64]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [65]:
df_record=pd.DataFrame([record])

In [66]:
df=pd.concat([df,df_record])

In [67]:
#df=df[df["CLASS"]!="Publication Expression"]

In [68]:
df

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,Membership,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,membership-person,person-person_uri;person-person_gender;person-...,WHOISWHO Person,WHOISWHO Person,TREE,membership-Membership;person-Person,NaN,NaN,NaN,NaN
1,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-directoryOrg2,directoryOrg2-directoryOrg2_uri;directoryOrg2-...,WHOISWHO directoryOrg second level,WHOISWHO directoryOrg second level,TREE,directoryOrg-Directory Organization;directoryO...,NaN,NaN,NaN,NaN
2,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opTheme-corporateBody,opTheme-opTheme_uri;corporateBody-corporateBod...,OP Themes and publication author,OP Themes and publication author,TREE,opTheme-OP Theme;corporateBody-corporateBody,NaN,NaN,NaN,NaN
3,eurovoc,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovoc-eurovocDomain-eurovocThesauri-eurovocC...,eurovoc-eurovoc_uri;eurovocDomain-eurovocDomai...,"Eurovoc domains, thesauri and concepts",Eurovoc concepts by thesauri and domain,TREE,eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;e...,NaN,NaN,NaN,NaN
4,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX rdfs: <http://www.w3.org/2000/01/rdf-sc...,eurovocConcept-aligment,eurovocConcept-eurovocConcept_uri,Eurovoc concept and aligments,Eurovoc concepts and external aligments,TREE,eurovocConcept-Eurovoc Concept;aligment-Aligment,NaN,NaN,NaN,NaN
5,nuts,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,nuts-nutsLevel0-nutsLevel1-nutsLevel2-nutsLevel3,nutsLevel0-nutsLevel0_uri;nutsLevel1-nutsLevel...,NUTS Tree,NUTS Tree,TREE,nuts-NUTS Classification;nutsLevel0-NUTS Level...,NaN,NaN,NaN,NaN
6,taxonomy,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,taxonomy-taxonomyType-taxonomyLevel1,taxonomy-taxonomy_def;taxonomyType-taxonomyTyp...,Taxonomies,Taxonomies,TREE,taxonomy-Taxonomies Classification;taxonomyTyp...,NaN,NaN,NaN,NaN
7,Taxonomy Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,taxonomyLevel1-taxonomyLevel2,taxonomyLevel1-taxonomyLevel1_uri;taxonomyLeve...,Taxonomy Level Children,Taxonomy Level Children,TREE,taxonomyLevel1-Taxonomy Level;taxonomyLevel2-T...,NaN,NaN,NaN,NaN
8,det,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,det-detLevel1-detLevel2,det-det_uri;detLevel1-detLevel1_uri;detLevel2-...,Digital Europa Thesaurus,Digital Europa Thesaurus,TREE,det-DET;detLevel1-DET Level;detLevel2-DET Level,NaN,NaN,NaN,NaN
9,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovocConcept-workType-work,eurovocConcept-eurovocConcept_uri;workType-wor...,Eurovoc concept and work types,Eurovoc concepts and works by type,TREE,eurovocConcept-Eurovoc Concept;workType-Work T...,NaN,NaN,NaN,NaN
10,DET Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,detLevel2-detLevel3,detLevel2-detLevel2_uri;detLevel3-detLevel3_uri,DET Children Level,DET Children Level,TREE,detLevel2-DET Level;detLevel3-DET Level,NaN,NaN,NaN,NaN
11,DET Level,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,detLevel1-eurovocConcept,detLevel1-detLevel1_uri;eurovocConcept-eurovoc...,DET Level to Eurovoc Concept,DET Level to Eurovoc Concept,TREE,detLevel1-DET Level;eurovocConcept-Eurovoc Con...,NaN,NaN,NaN,NaN
12,Continents,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,continent-continentName-country-language,continent-continent_uri;continentName-continen...,Languages by country and continent,Languages by country and continent,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
13,Continents,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,continent-continentName-country-org,continent-continent_uri;continentName-continen...,Continents countries and organisations,Continents countries and organisations those c...,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
14,org,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,org,org-org_desc;org-org_code;org-org_startDate;or...,Timeline organisations,Timeline organisations,TIMELINE,org-Organisation,NaN,NaN,NaN,NaN
15,eurun,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,eurun-corporateBody,eurun-eurun_uri;eurun-eurun_image;corporateBod...,WHOISWHO EURUN Suborganizations,WHOISWHO EURUN Suborganizations,TREE,eurun-European Union;corporateBody-corporateBody,NaN,corporateBody_country-dropdown;corporateBody_l...,corporateBody_country-Country;corporateBody_lo...,NaN
16,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-directoryOrg,directoryOrg-directoryOrg_uri;directoryOrg-dir...,WHOISWHO Suborganizations,WHOISWHO Suborganizations,TREE,corporateBody-corporateBody;directoryOrg-Direc...,NaN,NaN,NaN,NaN
17,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-membership,membership-membership_directoryOrg,WHOISWHO Membership,WHOISWHO Membership,TREE,directoryOrg-Directory Organization;membership...,NaN,NaN,NaN,NaN
18,Membership Type,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,membership-person,membership-membership_uri;membership-membershi...,WHOISWHO Membership Type,WHOISWHO Membership Type,TREE,membership-Membership Type;person-Person,membership_directoryOrg,NaN,NaN,NaN
19,Person,https://query.wikidata.org/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,person-article,article,WHOISWHO Wikipedia page,WHOISWHO Wikipedia page,WEBPAGE,article-Wikipedia Article,person_id,NaN,NaN,showWikipediaPage
20,opThemeMain,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,opThemeMain-opTheme,opThemeMain-opThemeMain_uri;opTheme-opTheme_uri,PUBLICATIONS - Publications by OP Theme,PUBLICATIONS - Publications by OP Theme,TREE,opThemeMain-Publications Themes;opTheme-OP Theme,NaN,NaN,NaN,NaN
21,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opThemeParent-opThemeChild,opThemeParent-opThemeParent_uri;opThemeChild-o...,OP Themes children,OP Themes children,TREE,opThemeParent-OP Theme;opThemeChild-OP Theme,NaN,NaN,NaN,NaN
0,Publication Document,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,expression-manifestation,expression-expression_uri;manifestation-manife...,Manifestation by Expression,Manifestation by Expression,TREE,expression-Publication Document;manifestation-...,,,manifestation_type-Manifestation Type,
0,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-publicationDocument,corporateBody-corporateBody_uri;publicationDoc...,Publications by CorporateBody,Publications by CorporateBody,TREE,corporateBody-corporateBody;publicationDocumen...,corporateBody_opTheme,,,

### PUBLICATIONS - Manifestations by Expression

In [32]:
#df=df[df["OPTION"]!="Manifestation by Expression"]

In [33]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [34]:
className="Publication Document"

In [35]:
hierarchy="expression-manifestation"

In [36]:
classes="expression-Publication Document;manifestation-Publication Manifestation"

In [37]:
properties="expression-expression_uri;manifestation-manifestation_isbn;manifestation-manifestation_uri;manifestation-manifestation_image;manifestation-manifestation_type"

In [38]:
option="Manifestation by Expression"

In [39]:
option_text="Manifestation by Expression"

In [40]:
query="""
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            SELECT DISTINCT ?expression ?expression_uri ?manifestation ?manifestation_uri ?manifestation_image ?manifestation_type
            where {
                    {
                    ?manifestation_uri cdm:manifestation_manifests_expression ?expression_uri.
                    ?manifestation_uri cdm:manifestation_has_thumbnail ?manifestation_image;
                                       cdm:manifestation_number_catalogue ?manifestation;
                                       cdm:manifestation_type ?manifestation_type.
                                       #cdm:manifestation_isbn ?manifestation_isbn.
                    ?expression_uri cdm:expression_title ?expression.
                    } 
                   filter(?expression_uri=<PARAMETER>)
                   }ORDER BY ?expression ?manifestation
    """

In [41]:
rowType="TREE"

In [42]:
parameters=""

In [43]:
tooltip="manifestation_type-Manifestation Type"

In [44]:
filters=""

In [45]:
function=""

In [46]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [47]:
df_record=pd.DataFrame([record])

In [48]:
df=pd.concat([df,df_record])

In [73]:
df

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,Membership,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,membership-person,person-person_uri;person-person_gender;person-...,WHOISWHO Person,WHOISWHO Person,TREE,membership-Membership;person-Person,NaN,NaN,NaN,NaN
1,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-directoryOrg2,directoryOrg2-directoryOrg2_uri;directoryOrg2-...,WHOISWHO directoryOrg second level,WHOISWHO directoryOrg second level,TREE,directoryOrg-Directory Organization;directoryO...,NaN,NaN,NaN,NaN
2,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opTheme-corporateBody,opTheme-opTheme_uri;corporateBody-corporateBod...,OP Themes and publication author,OP Themes and publication author,TREE,opTheme-OP Theme;corporateBody-corporateBody,NaN,NaN,NaN,NaN
3,eurovoc,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovoc-eurovocDomain-eurovocThesauri-eurovocC...,eurovoc-eurovoc_uri;eurovocDomain-eurovocDomai...,"Eurovoc domains, thesauri and concepts",Eurovoc concepts by thesauri and domain,TREE,eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;e...,NaN,NaN,NaN,NaN
4,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX rdfs: <http://www.w3.org/2000/01/rdf-sc...,eurovocConcept-aligment,eurovocConcept-eurovocConcept_uri,Eurovoc concept and aligments,Eurovoc concepts and external aligments,TREE,eurovocConcept-Eurovoc Concept;aligment-Aligment,NaN,NaN,NaN,NaN
5,nuts,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,nuts-nutsLevel0-nutsLevel1-nutsLevel2-nutsLevel3,nutsLevel0-nutsLevel0_uri;nutsLevel1-nutsLevel...,NUTS Tree,NUTS Tree,TREE,nuts-NUTS Classification;nutsLevel0-NUTS Level...,NaN,NaN,NaN,NaN
6,taxonomy,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,taxonomy-taxonomyType-taxonomyLevel1,taxonomy-taxonomy_def;taxonomyType-taxonomyTyp...,Taxonomies,Taxonomies,TREE,taxonomy-Taxonomies Classification;taxonomyTyp...,NaN,NaN,NaN,NaN
7,Taxonomy Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,taxonomyLevel1-taxonomyLevel2,taxonomyLevel1-taxonomyLevel1_uri;taxonomyLeve...,Taxonomy Level Children,Taxonomy Level Children,TREE,taxonomyLevel1-Taxonomy Level;taxonomyLevel2-T...,NaN,NaN,NaN,NaN
8,det,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,det-detLevel1-detLevel2,det-det_uri;detLevel1-detLevel1_uri;detLevel2-...,Digital Europa Thesaurus,Digital Europa Thesaurus,TREE,det-DET;detLevel1-DET Level;detLevel2-DET Level,NaN,NaN,NaN,NaN
9,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovocConcept-workType-work,eurovocConcept-eurovocConcept_uri;workType-wor...,Eurovoc concept and work types,Eurovoc concepts and works by type,TREE,eurovocConcept-Eurovoc Concept;workType-Work T...,NaN,NaN,NaN,NaN
10,DET Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,detLevel2-detLevel3,detLevel2-detLevel2_uri;detLevel3-detLevel3_uri,DET Children Level,DET Children Level,TREE,detLevel2-DET Level;detLevel3-DET Level,NaN,NaN,NaN,NaN
11,DET Level,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,detLevel1-eurovocConcept,detLevel1-detLevel1_uri;eurovocConcept-eurovoc...,DET Level to Eurovoc Concept,DET Level to Eurovoc Concept,TREE,detLevel1-DET Level;eurovocConcept-Eurovoc Con...,NaN,NaN,NaN,NaN
12,Continents,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,continent-continentName-country-language,continent-continent_uri;continentName-continen...,Languages by country and continent,Languages by country and continent,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
13,Continents,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,continent-continentName-country-org,continent-continent_uri;continentName-continen...,Continents countries and organisations,Continents countries and organisations those c...,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
14,org,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,org,org-org_desc;org-org_code;org-org_startDate;or...,Timeline organisations,Timeline organisations,TIMELINE,org-Organisation,NaN,NaN,NaN,NaN
15,eurun,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,eurun-corporateBody,eurun-eurun_uri;eurun-eurun_image;corporateBod...,WHOISWHO EURUN Suborganizations,WHOISWHO EURUN Suborganizations,TREE,eurun-European Union;corporateBody-corporateBody,NaN,corporateBody_country-dropdown;corporateBody_l...,corporateBody_country-Country;corporateBody_lo...,NaN
16,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-directoryOrg,directoryOrg-directoryOrg_uri;directoryOrg-dir...,WHOISWHO Suborganizations,WHOISWHO Suborganizations,TREE,corporateBody-corporateBody;directoryOrg-Direc...,NaN,NaN,NaN,NaN
17,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-membership,membership-membership_directoryOrg,WHOISWHO Membership,WHOISWHO Membership,TREE,directoryOrg-Directory Organization;membership...,NaN,NaN,NaN,NaN
18,Membership Type,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,membership-person,membership-membership_uri;membership-membershi...,WHOISWHO Membership Type,WHOISWHO Membership Type,TREE,membership-Membership Type;person-Person,membership_directoryOrg,NaN,NaN,NaN
19,Person,https://query.wikidata.org/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,person-article,article,WHOISWHO Wikipedia page,WHOISWHO Wikipedia page,WEBPAGE,article-Wikipedia Article,person_id,NaN,NaN,showWikipediaPage
20,opThemeMain,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,opThemeMain-opTheme,opThemeMain-opThemeMain_uri;opTheme-opTheme_uri,PUBLICATIONS - Publications by OP Theme,PUBLICATIONS - Publications by OP Theme,TREE,opThemeMain-Publications Themes;opTheme-OP Theme,NaN,NaN,NaN,NaN
21,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opThemeParent-opThemeChild,opThemeParent-opThemeParent_uri;opThemeChild-o...,OP Themes children,OP Themes children,TREE,opThemeParent-OP Theme;opThemeChild-OP Theme,NaN,NaN,NaN,NaN
0,Publication Document,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,expression-manifestation,expression-expression_uri;manifestation-manife...,Manifestation by Expression,Manifestation by Expression,TREE,expression-Publication Document;manifestation-...,,,manifestation_type-Manifestation Type,
0,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-publicationDocument,corporateBody-corporateBody_uri;publicationDoc...,Publications by CorporateBody,Publications by CorporateBody,TREE,corporateBody-corporateBody;publicationDocumen...,corporateBody_opTheme,,,

### PUBLICATIONS - OP Theme and Eurovoc concept (NOT IN FILE)

In [91]:
#df=df[df["OPTION"]!="Eurovoc Concepts by OP Themes"]

In [74]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [75]:
className="OP Theme"

In [76]:
hierarchy="opTheme-eurovocConcept"

In [77]:
classes="opTheme-OP Theme;eurovocConcept-Eurovoc Concept"

In [78]:
properties="opTheme-opTheme_uri;eurovocConcept-eurovocConcept_uri"

In [79]:
option="Eurovoc Concepts by OP Themes"

In [80]:
option_text="Eurovoc Concepts by OP Themes"

In [81]:
query="""
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            SELECT DISTINCT ?opTheme ?opTheme_uri ?eurovocConcept ?eurovocConcept_uri
            where {{?publicationDocument_uri cdm:publication_general_is_about_concept_op_theme ?opTheme_uri;
                       cdm:work_is_about_concept_eurovoc ?eurovocConcept_uri.
                    ?opTheme_uri skos:prefLabel ?opTheme.
                    ?eurovocConcept_uri skos:prefLabel ?eurovocConcept.
                    } 
                   filter(?opTheme_uri=<PARAMETER>)
                   FILTER(langMatches(lang(?eurovocConcept), "en")).
                   FILTER(langMatches(lang(?opTheme), "en")).
                   }ORDER BY ?opTheme ?eurovocConcept
    """

In [82]:
rowType="TREE"

In [83]:
parameters=""

In [84]:
tooltip=""

In [85]:
filters=""

In [86]:
function=""

In [87]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [88]:
df_record=pd.DataFrame([record])

In [89]:
df=pd.concat([df,df_record])

### PUBLICATIONS - Publications by Eurovoc concept (NOT IN FILE)

In [179]:
#df=df[df["OPTION"]!="PUBLICATIONS - Eurovoc Concepts by OP Themes"]

In [66]:
url="https://publications.europa.eu/webapi/rdf/sparql"

In [67]:
className="Eurovoc Concept"

In [68]:
hierarchy="eurovocConcept"

In [69]:
classes="opTheme-OP Theme;eurovocConcept-Eurovoc Concept"

In [70]:
properties="opTheme-opTheme_uri;eurovocConcept-eurovocConcept_uri"

In [71]:
option="PUBLICATIONS - Eurovoc Concepts by OP Themes"

In [72]:
option_text="PUBLICATIONS - Eurovoc Concepts by OP Themes"

In [74]:
query="""
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
    PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
            SELECT DISTINCT ?opTheme ?opTheme_uri ?eurovocConcept ?eurovocConcept_uri
            where {{?publicationDocument_uri cdm:publication_general_is_about_concept_op_theme ?opTheme_uri;
                       cdm:work_is_about_concept_eurovoc ?eurovocConcept_uri.
                    ?opTheme_uri skos:prefLabel ?opTheme.
                    ?eurovocConcept_uri skos:prefLabel ?eurovocConcept.
                    } 
                   filter(?opTheme_uri=<PARAMETER>)
                   FILTER(langMatches(lang(?eurovocConcept), "en")).
                   FILTER(langMatches(lang(?opTheme), "en")).
                   }ORDER BY ?opTheme ?eurovocConcept
    """

In [75]:
rowType="TREE"

In [83]:
parameters=""

In [84]:
tooltip=""

In [85]:
filters=""

In [86]:
function=""

In [87]:
record={'CLASS':className, 'URL':url, 'QUERY':query, 'HIERARCHY':hierarchy, 'PROPERTIES':properties,
        'OPTION':option,'OPTION_TEXT':option_text,'TYPE':rowType, 'CLASSES':classes, 'PARAMETERS':parameters, 'FILTERS':filters, 'TOOLTIP':tooltip,
       'FUNCTION':function}

In [77]:
df_record=pd.DataFrame([record])

In [78]:
df=pd.concat([df,df_record])

In [72]:
df

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,Membership,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,membership-person,person-person_uri;person-person_gender;person-...,WHOISWHO Person,WHOISWHO Person,TREE,membership-Membership;person-Person,NaN,NaN,NaN,NaN
1,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-directoryOrg2,directoryOrg2-directoryOrg2_uri;directoryOrg2-...,WHOISWHO directoryOrg second level,WHOISWHO directoryOrg second level,TREE,directoryOrg-Directory Organization;directoryO...,NaN,NaN,NaN,NaN
2,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opTheme-corporateBody,opTheme-opTheme_uri;corporateBody-corporateBod...,OP Themes and publication author,OP Themes and publication author,TREE,opTheme-OP Theme;corporateBody-corporateBody,NaN,NaN,NaN,NaN
3,eurovoc,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovoc-eurovocDomain-eurovocThesauri-eurovocC...,eurovoc-eurovoc_uri;eurovocDomain-eurovocDomai...,"Eurovoc domains, thesauri and concepts",Eurovoc concepts by thesauri and domain,TREE,eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;e...,NaN,NaN,NaN,NaN
4,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX rdfs: <http://www.w3.org/2000/01/rdf-sc...,eurovocConcept-aligment,eurovocConcept-eurovocConcept_uri,Eurovoc concept and aligments,Eurovoc concepts and external aligments,TREE,eurovocConcept-Eurovoc Concept;aligment-Aligment,NaN,NaN,NaN,NaN
5,nuts,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,nuts-nutsLevel0-nutsLevel1-nutsLevel2-nutsLevel3,nutsLevel0-nutsLevel0_uri;nutsLevel1-nutsLevel...,NUTS Tree,NUTS Tree,TREE,nuts-NUTS Classification;nutsLevel0-NUTS Level...,NaN,NaN,NaN,NaN
6,taxonomy,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,taxonomy-taxonomyType-taxonomyLevel1,taxonomy-taxonomy_def;taxonomyType-taxonomyTyp...,Taxonomies,Taxonomies,TREE,taxonomy-Taxonomies Classification;taxonomyTyp...,NaN,NaN,NaN,NaN
7,Taxonomy Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,taxonomyLevel1-taxonomyLevel2,taxonomyLevel1-taxonomyLevel1_uri;taxonomyLeve...,Taxonomy Level Children,Taxonomy Level Children,TREE,taxonomyLevel1-Taxonomy Level;taxonomyLevel2-T...,NaN,NaN,NaN,NaN
8,det,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,det-detLevel1-detLevel2,det-det_uri;detLevel1-detLevel1_uri;detLevel2-...,Digital Europa Thesaurus,Digital Europa Thesaurus,TREE,det-DET;detLevel1-DET Level;detLevel2-DET Level,NaN,NaN,NaN,NaN
9,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovocConcept-workType-work,eurovocConcept-eurovocConcept_uri;workType-wor...,Eurovoc concept and work types,Eurovoc concepts and works by type,TREE,eurovocConcept-Eurovoc Concept;workType-Work T...,NaN,NaN,NaN,NaN
10,DET Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,detLevel2-detLevel3,detLevel2-detLevel2_uri;detLevel3-detLevel3_uri,DET Children Level,DET Children Level,TREE,detLevel2-DET Level;detLevel3-DET Level,NaN,NaN,NaN,NaN
11,DET Level,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,detLevel1-eurovocConcept,detLevel1-detLevel1_uri;eurovocConcept-eurovoc...,DET Level to Eurovoc Concept,DET Level to Eurovoc Concept,TREE,detLevel1-DET Level;eurovocConcept-Eurovoc Con...,NaN,NaN,NaN,NaN
12,Continents,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,continent-continentName-country-language,continent-continent_uri;continentName-continen...,Languages by country and continent,Languages by country and continent,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
13,Continents,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,continent-continentName-country-org,continent-continent_uri;continentName-continen...,Continents countries and organisations,Continents countries and organisations those c...,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
14,org,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,org,org-org_desc;org-org_code;org-org_startDate;or...,Timeline organisations,Timeline organisations,TIMELINE,org-Organisation,NaN,NaN,NaN,NaN
15,eurun,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,eurun-corporateBody,eurun-eurun_uri;eurun-eurun_image;corporateBod...,WHOISWHO EURUN Suborganizations,WHOISWHO EURUN Suborganizations,TREE,eurun-European Union;corporateBody-corporateBody,NaN,corporateBody_country-dropdown;corporateBody_l...,corporateBody_country-Country;corporateBody_lo...,NaN
16,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-directoryOrg,directoryOrg-directoryOrg_uri;directoryOrg-dir...,WHOISWHO Suborganizations,WHOISWHO Suborganizations,TREE,corporateBody-corporateBody;directoryOrg-Direc...,NaN,NaN,NaN,NaN
17,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-membership,membership-membership_directoryOrg,WHOISWHO Membership,WHOISWHO Membership,TREE,directoryOrg-Directory Organization;membership...,NaN,NaN,NaN,NaN
18,Membership Type,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,membership-person,membership-membership_uri;membership-membershi...,WHOISWHO Membership Type,WHOISWHO Membership Type,TREE,membership-Membership Type;person-Person,membership_directoryOrg,NaN,NaN,NaN
19,Person,https://query.wikidata.org/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,person-article,article,WHOISWHO Wikipedia page,WHOISWHO Wikipedia page,WEBPAGE,article-Wikipedia Article,person_id,NaN,NaN,showWikipediaPage
20,opThemeMain,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,opThemeMain-opTheme,opThemeMain-opThemeMain_uri;opTheme-opTheme_uri,PUBLICATIONS - Publications by OP Theme,PUBLICATIONS - Publications by OP Theme,TREE,opThemeMain-Publications Themes;opTheme-OP Theme,NaN,NaN,NaN,NaN
21,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opThemeParent-opThemeChild,opThemeParent-opThemeParent_uri;opThemeChild-o...,OP Themes children,OP Themes children,TREE,opThemeParent-OP Theme;opThemeChild-OP Theme,NaN,NaN,NaN,NaN
0,Publication Document,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,expression-manifestation,expression-expression_uri;manifestation-manife...,Manifestation by Expression,Manifestation by Expression,TREE,expression-Publication Document;manifestation-...,,,manifestation_type-Manifestation Type,
0,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-publicationDocument,corporateBody-corporateBody_uri;publicationDoc...,Publications by CorporateBody,Publications by CorporateBody,TREE,corporateBody-corporateBody;publicationDocumen...,corporateBody_opTheme,,,

In [108]:
df.to_csv("../networkGraph2/txt/config_basicMode.txt", sep='\t',index=False,encoding="utf-8")

In [107]:
df=pd.concat([df[20:-3],df[:20],df.tail(3)])

In [101]:
df[:20]

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
0,Membership,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,membership-person,person-person_uri;person-person_gender;person-...,WHOISWHO Person,WHOISWHO Person,TREE,membership-Membership;person-Person,NaN,NaN,NaN,NaN
1,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-directoryOrg2,directoryOrg2-directoryOrg2_uri;directoryOrg2-...,WHOISWHO directoryOrg second level,WHOISWHO directoryOrg second level,TREE,directoryOrg-Directory Organization;directoryO...,NaN,NaN,NaN,NaN
2,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opTheme-corporateBody,opTheme-opTheme_uri;corporateBody-corporateBod...,OP Themes and publication author,OP Themes and publication author,TREE,opTheme-OP Theme;corporateBody-corporateBody,NaN,NaN,NaN,NaN
3,eurovoc,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovoc-eurovocDomain-eurovocThesauri-eurovocC...,eurovoc-eurovoc_uri;eurovocDomain-eurovocDomai...,"Eurovoc domains, thesauri and concepts",Eurovoc concepts by thesauri and domain,TREE,eurovoc-Eurovoc;eurovocDomain-Eurovoc Domain;e...,NaN,NaN,NaN,NaN
4,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX rdfs: <http://www.w3.org/2000/01/rdf-sc...,eurovocConcept-aligment,eurovocConcept-eurovocConcept_uri,Eurovoc concept and aligments,Eurovoc concepts and external aligments,TREE,eurovocConcept-Eurovoc Concept;aligment-Aligment,NaN,NaN,NaN,NaN
5,nuts,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,nuts-nutsLevel0-nutsLevel1-nutsLevel2-nutsLevel3,nutsLevel0-nutsLevel0_uri;nutsLevel1-nutsLevel...,NUTS Tree,NUTS Tree,TREE,nuts-NUTS Classification;nutsLevel0-NUTS Level...,NaN,NaN,NaN,NaN
6,taxonomy,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,taxonomy-taxonomyType-taxonomyLevel1,taxonomy-taxonomy_def;taxonomyType-taxonomyTyp...,Taxonomies,Taxonomies,TREE,taxonomy-Taxonomies Classification;taxonomyTyp...,NaN,NaN,NaN,NaN
7,Taxonomy Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,taxonomyLevel1-taxonomyLevel2,taxonomyLevel1-taxonomyLevel1_uri;taxonomyLeve...,Taxonomy Level Children,Taxonomy Level Children,TREE,taxonomyLevel1-Taxonomy Level;taxonomyLevel2-T...,NaN,NaN,NaN,NaN
8,det,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,det-detLevel1-detLevel2,det-det_uri;detLevel1-detLevel1_uri;detLevel2-...,Digital Europa Thesaurus,Digital Europa Thesaurus,TREE,det-DET;detLevel1-DET Level;detLevel2-DET Level,NaN,NaN,NaN,NaN
9,Eurovoc Concept,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,eurovocConcept-workType-work,eurovocConcept-eurovocConcept_uri;workType-wor...,Eurovoc concept and work types,Eurovoc concepts and works by type,TREE,eurovocConcept-Eurovoc Concept;workType-Work T...,NaN,NaN,NaN,NaN
10,DET Level,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,detLevel2-detLevel3,detLevel2-detLevel2_uri;detLevel3-detLevel3_uri,DET Children Level,DET Children Level,TREE,detLevel2-DET Level;detLevel3-DET Level,NaN,NaN,NaN,NaN
11,DET Level,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,detLevel1-eurovocConcept,detLevel1-detLevel1_uri;eurovocConcept-eurovoc...,DET Level to Eurovoc Concept,DET Level to Eurovoc Concept,TREE,detLevel1-DET Level;eurovocConcept-Eurovoc Con...,NaN,NaN,NaN,NaN
12,Continents,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,continent-continentName-country-language,continent-continent_uri;continentName-continen...,Languages by country and continent,Languages by country and continent,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
13,Continents,https://publications.europa.eu/webapi/rdf/sparql,PREFIX xsd: <http://www.w3.org/2001/XMLSchema#...,continent-continentName-country-org,continent-continent_uri;continentName-continen...,Continents countries and organisations,Continents countries and organisations those c...,TREE,continent-Continents;continentName-Continent;c...,NaN,NaN,NaN,NaN
14,org,https://publications.europa.eu/webapi/rdf/sparql,PREFIX skos: <http://www.w3.org/2004/02/skos/c...,org,org-org_desc;org-org_code;org-org_startDate;or...,Timeline organisations,Timeline organisations,TIMELINE,org-Organisation,NaN,NaN,NaN,NaN
15,eurun,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,eurun-corporateBody,eurun-eurun_uri;eurun-eurun_image;corporateBod...,WHOISWHO EURUN Suborganizations,WHOISWHO EURUN Suborganizations,TREE,eurun-European Union;corporateBody-corporateBody,NaN,corporateBody_country-dropdown;corporateBody_l...,corporateBody_country-Country;corporateBody_lo...,NaN
16,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-directoryOrg,directoryOrg-directoryOrg_uri;directoryOrg-dir...,WHOISWHO Suborganizations,WHOISWHO Suborganizations,TREE,corporateBody-corporateBody;directoryOrg-Direc...,NaN,NaN,NaN,NaN
17,Directory Organization,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,directoryOrg-membership,membership-membership_directoryOrg,WHOISWHO Membership,WHOISWHO Membership,TREE,directoryOrg-Directory Organization;membership...,NaN,NaN,NaN,NaN
18,Membership Type,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,membership-person,membership-membership_uri;membership-membershi...,WHOISWHO Membership Type,WHOISWHO Membership Type,TREE,membership-Membership Type;person-Person,membership_directoryOrg,NaN,NaN,NaN
19,Person,https://query.wikidata.org/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,person-article,article,WHOISWHO Wikipedia page,WHOISWHO Wikipedia page,WEBPAGE,article-Wikipedia Article,person_id,NaN,NaN,showWikipediaPage

In [97]:
df[20:-3]

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
20,opThemeMain,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/XMLS...,opThemeMain-opTheme,opThemeMain-opThemeMain_uri;opTheme-opTheme_uri,PUBLICATIONS - Publications by OP Theme,PUBLICATIONS - Publications by OP Theme,TREE,opThemeMain-Publications Themes;opTheme-OP Theme,NaN,NaN,NaN,NaN

In [103]:
df.tail(3)

,CLASS,URL,QUERY,HIERARCHY,PROPERTIES,OPTION,OPTION_TEXT,TYPE,CLASSES,PARAMETERS,FILTERS,TOOLTIP,FUNCTION
21,OP Theme,https://publications.europa.eu/webapi/rdf/sparql,\n PREFIX xsd: <http://www.w3.org/2001/...,opThemeParent-opThemeChild,opThemeParent-opThemeParent_uri;opThemeChild-o...,OP Themes children,OP Themes children,TREE,opThemeParent-OP Theme;opThemeChild-OP Theme,NaN,NaN,NaN,NaN
0,Publication Document,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,expression-manifestation,expression-expression_uri;manifestation-manife...,Manifestation by Expression,Manifestation by Expression,TREE,expression-Publication Document;manifestation-...,,,manifestation_type-Manifestation Type,
0,corporateBody,https://publications.europa.eu/webapi/rdf/sparql,\nPREFIX xsd: <http://www.w3.org/2001/XMLSchem...,corporateBody-publicationDocument,corporateBody-corporateBody_uri;publicationDoc...,Publications by CorporateBody,Publications by CorporateBody,TREE,corporateBody-corporateBody;publicationDocumen...,corporateBody_opTheme,,,

In [43]:
#df=df[df["OPTION"]!="WHOISWHO Wikipedia page"]

## Expert Mode

In [24]:
filename="../networkGraph2/txt/config_expertMode.txt"

In [25]:
df_ex=pd.read_csv(filename, sep='\t')

In [26]:
df_ex

,URI,ENDPOINT
0,http://publications.europa.eu/resource/authori...,https://publications.europa.eu/webapi/rdf/sparql
1,http://publications.europa.eu/resource/authori...,https://publications.europa.eu/webapi/rdf/sparql
2,http://publications.europa.eu/resource/authori...,https://publications.europa.eu/webapi/rdf/sparql
3,http://data.europa.eu/88u/dataset/covid-19-cor...,https://data.europa.eu/euodp/sparqlep